# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

Vagrant.configure("2") do |config|

  config.vm.box = "CentOS-6.4-x86_64-v20130427"
  config.vm.box_url = "http://cosmos10.hi.inet:8080/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box"

  config.vm.provision :puppet, :module_path =>  "modules" do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "site.pp"
    puppet.module_path = "modules"
    puppet.options = "--environment vagrant"
  end

  config.vm.define :master do |master_config|
    master_config.vm.network :private_network, ip: "192.168.11.10"
    master_config.vm.hostname = "cosmos-master.vagrant"
  end

  config.vm.define :slave1 do |slave1_config|
    slave1_config.vm.network :private_network, ip: "192.168.11.21"
    slave1_config.vm.hostname = "cosmos-slave1.vagrant"
  end

  config.vm.define :slave2 do |slave2_config|
    slave2_config.vm.network :private_network, ip: "192.168.11.22"
    slave2_config.vm.hostname = "cosmos-slave2.vagrant"
  end
end
