
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_url_ServerPathVector
#define _H_SAMSON_url_ServerPathVector


#include <samson/modules/url/ServerPathVector_base.h>


namespace samson{
namespace url{


	class ServerPathVector : public ServerPathVector_base
	{
	public:
		bool contains( ServerPathCount * path) {
		  if( serverPath_length == 0)
		    return false;

		  for (int i = 0  ; i < serverPath_length ; i++)
		    if(serverPath[i].isEqual(path))
		      return true;

		  return false;
		}
	};


} // end of namespace samson
} // end of namespace url

#endif
