
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_snalight_Metric_Cluster
#define _H_SAMSON_snalight_Metric_Cluster


#include <samson/modules/snalight/Metric_Cluster_base.h>


namespace samson{
namespace snalight{


	class Metric_Cluster : public Metric_Cluster_base
	{
	};


} // end of namespace samson
} // end of namespace snalight

#endif
