
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_snalight_Metric_Reach_Comm
#define _H_SAMSON_snalight_Metric_Reach_Comm


#include <samson/modules/snalight/Metric_Reach_Comm_base.h>


namespace samson{
namespace snalight{


	class Metric_Reach_Comm : public Metric_Reach_Comm_base
	{
	};


} // end of namespace samson
} // end of namespace snalight

#endif
