#
# Copyright (c) 2013-2014 Telefónica Investigación y Desarrollo S.A.U.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

Vagrant.configure("2") do |config|
  config.vm.box = "centos64-guestadditions"
  config.vm.box_url = "http://cosmos10.hi.inet:8080/vagrant-boxes/CentOS-6.4-i386-v20130427.box"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "base-hadoop.pp"
    puppet.module_path = "modules"
  end

  config.vm.define :master do |master_config|
    master_config.vm.network :private_network, ip: "192.168.10.10"
    master_config.vm.hostname = "master"
  end

  config.vm.define :slave1 do |slave1_config|
    slave1_config.vm.network :private_network, ip: "192.168.10.21"
    slave1_config.vm.hostname = "slave1"
  end

  config.vm.define :slave2 do |slave2_config|
    slave2_config.vm.network :private_network, ip: "192.168.10.22"
    slave2_config.vm.hostname = "slave2"
  end
end
