
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_mob_script_parse
#define _H_SAMSON_mob_script_parse


#include <samson/module/samson.h>


namespace samson{
namespace mob{


	class script_parse : public samson::Script
	{

	public:


#ifdef INFO_COMMENT //Just to include a comment without conflicting anything
// If interface changes and you do not recreate this file, consider updating this information (and of course, the module file)

input: txt txt  

extendedHelp: 		Script to parse input files.

#endif // de INFO_COMMENT



	};


} // end of namespace mob
} // end of namespace samson

#endif
