.TH SAMSON\-CDR 7 2011-07-08 "Samson" "Samson Module Libraries"
.SH NAME
samson\-cdr \- call data record processing
.SH DESCRIPTION
The samson CDR library parses and processes CDRs from TME and various formats from O2 UK.

.SH DATA TYPES
  Date (UInt8 year, UInt8 month, UInt8 day, UInt days_2000, UInt8 week_day)
  Time (UInt8 hour, UInt8 minute, UInt8 seconds)
  CDR  (UInt node, Date date, Time time, UInt duration)
  User (UInt  id,  UInt  titularId, UInt8 type, Date activationDate, UInt activationCode,
        UInt8 age, UInt8 province,  UInt8 sex,  Date churnDate,      UInt8 churnCode)

.SH FUNCTIONS
  Generator  fake_cdrs(out UInt-CDR)
  Generator  fake_users(out UInt-User)
  Parser     parse_cdrs(out UInt-CDR)
  Parser     parse_users(out UInt-User)
  Parser     parse_users_O2UK(out UInt-User)
  parserOut  select_cdrs(in UInt-CDR)
  Map        spread_cdrs_to_links(in UInt-CDR, out UInt-UInt)
  Map        spread_cdrs_to_links2(in UInt-CDR, out UInt2-Void)
  Reduce     remove_duplicated_cdrs(in UInt-CDR, out UInt-CDR)

.SH SCRIPTS
No scripts are defined in this module.

.SH SEE ALSO
.BR samson (1),
.BR samson-example (7),
.BR samson-graph (7),
.BR samson-moduletemplate (7),
.BR samson-osn (7),
.BR samson-sna (7),
.BR samson-sort (7),
.BR samson-system (7),
.BR samson-terasort (7),
.BR samson-test (7),
.BR samson-txt (7),
.BR samson-urlbenchmark (7)
