.TH SAMSON\-TXT 7 2011-07-08 "Samson" "Samson Module Libraries"
.SH NAME
samson\-txt \- text processing
.SH DESCRIPTION
The samson TXT library processes texts. Included is the typical example of
word count and collocations.

.SH DATA TYPES
  Collocation (String w1, String w2)
  PairInts    (UInt i1, UInt i2)
  CountData   (String word, UInt count)
  Stripe      (vector CountData colList)

.SH FUNCTIONS
  Parser      parser_words (out String-UInt)
  Parser      parser_collocations_pairs (out Collocation-UInt)
  Parser      parser_collocations_stripes (out String-Stripe)
  Reduce      word_count (in String-UInt, out String-UInt)
  Reduce      collocation_count (in Collocation-UInt, out Collocation-UInt)
  Reduce      collocation_count_stripes (in String-Stripe, out String-Stripe)
  Reduce      word_count_accumulate (in String-UInt, in String-UInt, out String-UInt)
  Parser      export_words (in String-UInt)
  ParserOut   export_collocations (in Collocation-UInt)
  ParserOut   export_collocations_stripes (in String-Strip)

.SH SCRIPTS
  demo    -> remove_operation;
             set_operation
             [ These commands aren't yet supported ]

  words   -> parser_words;
             word_count;
             export_words

.SH SEE ALSO
.BR samson (1),
.BR samson-cdr (7),
.BR samson-example (7),
.BR samson-graph (7),
.BR samson-moduletemplate (7),
.BR samson-osn (7),
.BR samson-sna (7),
.BR samson-sort (7),
.BR samson-system (7),
.BR samson-terasort (7),
.BR samson-test (7),
.BR samson-urlbenchmark (7)
