.TH SAMSON\-OSN 7 2011-07-08 "Samson" "Samson Module Libraries"
.SH NAME
samson\-osn \- O2 mobile web access log processing 
.SH DESCRIPTION
The samson OSN library processes the log files of O2 about their web accesses from cell phones.

.SH DATA TYPES
  Date           (UInt8 year, UInt8 month, UInt8 day, UInt days_2000, UInt8 week_day)
  Time           (UInt8 hour, UInt8 minute, UInt8 seconds)
  URL            (String completeURL, String url_host, String url_dir, String url_page, String url_query, String url_locDoc)
  URLConnection  (UInt64 msisdn, URL url, Date date, Time time, UInt16 status, String MIMEcontent, String userAgent, UInt8 method)
  Count          (UInt count, String element)
  CountF         (Float count, String element)

.SH FUNCTIONS
  Parser     parse_urls (out UInt64-URLConnection)
  Map        map_urls_to_kv_to_compute_sites_visited (in UInt64-URLConnection, out String-UInt, out UInt-UInt)
  Map        map_site_user (in UInt64-URLConnection, out String-UInt, out UInt-UInt)
  Map        map_url_user (in UInt64-URLConnection, out String-UInt, out UInt-UInt)
  Map        map_urls_by_hour (in UInt64-URLConnection, out String-UInt, out UInt-UInt)
  Map        map_applications (in UInt64-URLConnection, out String-UInt, out String-UInt, out UInt-UInt)
  Map        map_extract_logs_by_useragent (in UInt64-URLConnection, out String-UInt, out UInt-UInt)
  Map        map_filter_in_by_status (in String-URLConnection, out String-URLConnection, out UInt-UInt)
  Map        map_filter_out_by_status (in String-URLConnection, out String-URLConnection, out UInt-UInt)
  Reduce     red_compute_sites_visited (in String-UInt, out UInt-Count)
  Reduce     red_select_N_sites (in UInt-Count, out Count-Void)
  Reduce     red_compute_total_elements (in UInt-Count, out UInt-Void)
  Reduce     red_compute_total_and_set (in UInt-UInt) .
  ParserOut  export_connections (in String-URLConnection)
  ParserOut  export_report (in UInt-Count)
  ParserOut  export_N_sites (in Count-Void)
  ParserOut  export_total (in UInt-Void)

.SH SCRIPTS
  Bytemobile_req_1  -> parse_urls;
                       map_urls_to_kv_to_compute_sites_visited;
                       red_compute_total_and_set;
                       red_compute_sites_visited;
                       export_report;
                       red_select_N_sites;
                       export_N_sites

  Bytemobile_req_2  -> parse_urls;
                       map_site_user;
                       red_compute_total_and_set;
                       red_compute_sites_visited;
                       export_report;
                       red_compute_total_elements;
                       export_total

  Bytemobile_req_3  -> parse_urls;
                       map_site_user;
                       red_compute_total_and_set;
                       red_compute_sites_visited;
                       export_report;
                       red_compute_total_elements;
                       export_total

  Bytemobile_req_5  -> parse_urls;
                       map_url_user;
                       red_compute_total_and_set;
                       red_compute_sites_visited;
                       export_report;
                       red_compute_total_elements;
                       export_total

  Bytemobile_req_6  -> parse_urls;
                       map_url_user;
                       red_compute_total_and_set;
                       red_compute_sites_visited;
                       export_report;
                       red_compute_total_elements;
                       export_total

  Bytemobile_req_7  -> parse_urls;
                       map_applications;
                       red_compute_total_and_set;
                       red_compute_sites_visited;
                       export_report;
                       red_compute_sites_visited;
                       export_report;
                       red_compute_total_elements;
                       export_total

.SH SEE ALSO
.BR samson (1),
.BR samson-cdr (7),
.BR samson-example (7),
.BR samson-graph (7),
.BR samson-moduletemplate (7),
.BR samson-sna (7),
.BR samson-sort (7),
.BR samson-system (7),
.BR samson-terasort (7),
.BR samson-test (7),
.BR samson-txt (7),
.BR samson-urlbenchmark (7)
