
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_sna_Community
#define _H_SAMSON_sna_Community


#include <samson/modules/sna/Community_base.h>


namespace samson{
namespace sna{


	class Community : public Community_base
	{
	};


} // end of namespace samson
} // end of namespace sna

#endif
