
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_passive_location_CompleteTMSI
#define _H_SAMSON_passive_location_CompleteTMSI


#include <samson/modules/passive_location/CompleteTMSI_base.h>


namespace samson{
namespace passive_location{


	class CompleteTMSI : public CompleteTMSI_base
	{
	};


} // end of namespace samson
} // end of namespace passive_location

#endif
