
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_sna_parse_graph
#define _H_SAMSON_sna_parse_graph


#include <samson/module/samson.h>


namespace samson{
namespace sna{


	class parse_graph : public samson::Script
	{

	public:




	};


} // end of namespace samson
} // end of namespace sna

#endif
