
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_level_ValTimed
#define _H_SAMSON_level_ValTimed


#include <samson/modules/level/ValTimed_base.h>


namespace samson{
namespace level{


	class ValTimed : public ValTimed_base
	{
	};


} // end of namespace samson
} // end of namespace level

#endif
