all:
	make -C system
	make -C txt
	make -C txt_md
	make -C example
	make -C tienda
	make -C cdr
	make -C mob
	make -C mob2
	make -C graph
	make -C sna
	make -C snalight
	make -C osn
	make -C url
	make -C urlbenchmark
	make -C sort
	make -C terasort
	make -C testtime
	make -C testcomparefunctions
	make -C hit
	make -C gg
	make -C page_rank
	make -C wiki

release:
	make release -C system
	make release -C txt
	make release -C txt_md
	make release -C example
	make release -C tienda
	make release -C cdr
	make release -C mob
	make release -C mob2
	make release -C graph
	make release -C sna
	make release -C snalight
	make release -C osn
	make release -C url
	make release -C urlbenchmark
	make release -C sort
	make release -C terasort
	make release -C testtime
	make release -C testcomparefunctions
	make release -C hit
	make release -C gg
	make release -C page_rank
	make release -C wiki

reset:
	make reset -C system
	make reset -C txt 
	make reset -C txt_md
	make reset -C example 
	make reset -C tienda 
	make reset -C cdr
	make reset -C mob
	make reset -C mob2
	make reset -C graph
	make reset -C sna
	make reset -C snalight 
	make reset -C osn 
	make reset -C url 
	make reset -C urlbenchmark 
	make reset -C sort
	make reset -C terasort
	make reset -C testtime
	make reset -C testcomparefunctions
	make reset -C hit
	make reset -C gg
	make reset -C page_rank
	make reset -C wiki

eclipse:
	make eclipse -C system
	make eclipse -C txt_md
	make eclipse -C example
	make eclipse -C tienda
	make eclipse -C cdr
	make eclipse -C mob
	make eclipse -C mob2
	make eclipse -C graph
	make eclipse -C sna
	make eclipse -C snalight
	make eclipse -C osn
	make eclipse -C url
	make eclipse -C urlbenchmark
	make eclipse -C sort
	make eclipse -C terasort
	make eclipse -C testtime
