ifndef SAMSON_HOME
SAMSON_HOME=/opt/samson
endif
all:
	SAMSON_HOME=$(SAMSON_HOME) make -C system
	SAMSON_HOME=$(SAMSON_HOME) make -C txt
	SAMSON_HOME=$(SAMSON_HOME) make -C txt_md
	SAMSON_HOME=$(SAMSON_HOME) make -C example
	SAMSON_HOME=$(SAMSON_HOME) make -C tienda
	SAMSON_HOME=$(SAMSON_HOME) make -C cdr
	SAMSON_HOME=$(SAMSON_HOME) make -C mobility
	SAMSON_HOME=$(SAMSON_HOME) make -C mob
	SAMSON_HOME=$(SAMSON_HOME) make -C mob2
	SAMSON_HOME=$(SAMSON_HOME) make -C passive_location
	SAMSON_HOME=$(SAMSON_HOME) make -C graph
	SAMSON_HOME=$(SAMSON_HOME) make -C sna
	SAMSON_HOME=$(SAMSON_HOME) make -C snalight
	SAMSON_HOME=$(SAMSON_HOME) make -C osn
	SAMSON_HOME=$(SAMSON_HOME) make -C url
	SAMSON_HOME=$(SAMSON_HOME) make -C urlbenchmark
	SAMSON_HOME=$(SAMSON_HOME) make -C sort
	SAMSON_HOME=$(SAMSON_HOME) make -C terasort
	SAMSON_HOME=$(SAMSON_HOME) make -C testtime
	SAMSON_HOME=$(SAMSON_HOME) make -C testcomparefunctions
	SAMSON_HOME=$(SAMSON_HOME) make -C hit
	SAMSON_HOME=$(SAMSON_HOME) make -C gg
	SAMSON_HOME=$(SAMSON_HOME) make -C page_rank
	SAMSON_HOME=$(SAMSON_HOME) make -C wiki
	SAMSON_HOME=$(SAMSON_HOME) make -C simple_mobility

release:
	SAMSON_HOME=$(SAMSON_HOME) make release -C system
	SAMSON_HOME=$(SAMSON_HOME) make release -C txt
	SAMSON_HOME=$(SAMSON_HOME) make release -C txt_md
	SAMSON_HOME=$(SAMSON_HOME) make release -C example
	SAMSON_HOME=$(SAMSON_HOME) make release -C tienda
	SAMSON_HOME=$(SAMSON_HOME) make release -C cdr
	SAMSON_HOME=$(SAMSON_HOME) make release -C mobility
	SAMSON_HOME=$(SAMSON_HOME) make release -C mob
	SAMSON_HOME=$(SAMSON_HOME) make release -C mob2
	SAMSON_HOME=$(SAMSON_HOME) make release -C passive_location
	SAMSON_HOME=$(SAMSON_HOME) make release -C graph
	SAMSON_HOME=$(SAMSON_HOME) make release -C sna
	SAMSON_HOME=$(SAMSON_HOME) make release -C snalight
	SAMSON_HOME=$(SAMSON_HOME) make release -C osn
	SAMSON_HOME=$(SAMSON_HOME) make release -C url
	SAMSON_HOME=$(SAMSON_HOME) make release -C urlbenchmark
	SAMSON_HOME=$(SAMSON_HOME) make release -C sort
	SAMSON_HOME=$(SAMSON_HOME) make release -C terasort
	SAMSON_HOME=$(SAMSON_HOME) make release -C testtime
	SAMSON_HOME=$(SAMSON_HOME) make release -C testcomparefunctions
	SAMSON_HOME=$(SAMSON_HOME) make release -C hit
	SAMSON_HOME=$(SAMSON_HOME) make release -C gg
	SAMSON_HOME=$(SAMSON_HOME) make release -C page_rank
	SAMSON_HOME=$(SAMSON_HOME) make release -C wiki
	SAMSON_HOME=$(SAMSON_HOME) make release -C simple_mobility



reset:
	SAMSON_HOME=$(SAMSON_HOME) make reset -C system
	SAMSON_HOME=$(SAMSON_HOME) make reset -C txt 
	SAMSON_HOME=$(SAMSON_HOME) make reset -C txt_md
	SAMSON_HOME=$(SAMSON_HOME) make reset -C example 
	SAMSON_HOME=$(SAMSON_HOME) make reset -C tienda 
	SAMSON_HOME=$(SAMSON_HOME) make reset -C cdr
	SAMSON_HOME=$(SAMSON_HOME) make reset -C mobility
	SAMSON_HOME=$(SAMSON_HOME) make reset -C mob
	SAMSON_HOME=$(SAMSON_HOME) make reset -C mob2
	SAMSON_HOME=$(SAMSON_HOME) make reset -C passive_location
	SAMSON_HOME=$(SAMSON_HOME) make reset -C graph
	SAMSON_HOME=$(SAMSON_HOME) make reset -C sna
	SAMSON_HOME=$(SAMSON_HOME) make reset -C snalight 
	SAMSON_HOME=$(SAMSON_HOME) make reset -C osn 
	SAMSON_HOME=$(SAMSON_HOME) make reset -C url 
	SAMSON_HOME=$(SAMSON_HOME) make reset -C urlbenchmark 
	SAMSON_HOME=$(SAMSON_HOME) make reset -C sort
	SAMSON_HOME=$(SAMSON_HOME) make reset -C terasort
	SAMSON_HOME=$(SAMSON_HOME) make reset -C testtime
	SAMSON_HOME=$(SAMSON_HOME) make reset -C testcomparefunctions
	SAMSON_HOME=$(SAMSON_HOME) make reset -C hit
	SAMSON_HOME=$(SAMSON_HOME) make reset -C gg
	SAMSON_HOME=$(SAMSON_HOME) make reset -C page_rank
	SAMSON_HOME=$(SAMSON_HOME) make reset -C wiki


install:
	SAMSON_HOME=$(SAMSON_HOME) make install -C system
	SAMSON_HOME=$(SAMSON_HOME) make install -C txt 
	SAMSON_HOME=$(SAMSON_HOME) make install -C txt_md
	SAMSON_HOME=$(SAMSON_HOME) make install -C example 
	SAMSON_HOME=$(SAMSON_HOME) make install -C tienda 
	SAMSON_HOME=$(SAMSON_HOME) make install -C cdr
	SAMSON_HOME=$(SAMSON_HOME) make install -C mob
	SAMSON_HOME=$(SAMSON_HOME) make install -C mob2
	SAMSON_HOME=$(SAMSON_HOME) make install -C passive_location
	SAMSON_HOME=$(SAMSON_HOME) make install -C graph
	SAMSON_HOME=$(SAMSON_HOME) make install -C sna
	SAMSON_HOME=$(SAMSON_HOME) make install -C snalight 
	SAMSON_HOME=$(SAMSON_HOME) make install -C osn 
	SAMSON_HOME=$(SAMSON_HOME) make install -C url 
	SAMSON_HOME=$(SAMSON_HOME) make install -C urlbenchmark 
	SAMSON_HOME=$(SAMSON_HOME) make install -C sort
	SAMSON_HOME=$(SAMSON_HOME) make install -C terasort
	SAMSON_HOME=$(SAMSON_HOME) make install -C testtime
	SAMSON_HOME=$(SAMSON_HOME) make install -C testcomparefunctions
	SAMSON_HOME=$(SAMSON_HOME) make install -C hit
	SAMSON_HOME=$(SAMSON_HOME) make install -C gg
	SAMSON_HOME=$(SAMSON_HOME) make install -C page_rank
	SAMSON_HOME=$(SAMSON_HOME) make install -C wiki
	SAMSON_HOME=$(SAMSON_HOME) make install -C simple_mobility
test:
	SAMSON_HOME=$(SAMSON_HOME) make test -C txt
	SAMSON_HOME=$(SAMSON_HOME) make test -C sort
	SAMSON_HOME=$(SAMSON_HOME) make test -C urlbenchmark

eclipse:
	SAMSON_HOME=$(SAMSON_HOME) make eclipse -C system
	SAMSON_HOME=$(SAMSON_HOME) make eclipse -C txt_md
	SAMSON_HOME=$(SAMSON_HOME) make eclipse -C passive_location
	SAMSON_HOME=$(SAMSON_HOME) make eclipse -C example
	SAMSON_HOME=$(SAMSON_HOME) make eclipse -C tienda
	SAMSON_HOME=$(SAMSON_HOME) make eclipse -C cdr
	SAMSON_HOME=$(SAMSON_HOME) make eclipse -C mob
	SAMSON_HOME=$(SAMSON_HOME) make eclipse -C mob2
	SAMSON_HOME=$(SAMSON_HOME) make eclipse -C graph
	SAMSON_HOME=$(SAMSON_HOME) make eclipse -C sna
	SAMSON_HOME=$(SAMSON_HOME) make eclipse -C snalight
	SAMSON_HOME=$(SAMSON_HOME) make eclipse -C osn
	SAMSON_HOME=$(SAMSON_HOME) make eclipse -C url
	SAMSON_HOME=$(SAMSON_HOME) make eclipse -C urlbenchmark
	SAMSON_HOME=$(SAMSON_HOME) make eclipse -C sort
	SAMSON_HOME=$(SAMSON_HOME) make eclipse -C terasort
	SAMSON_HOME=$(SAMSON_HOME) make eclipse -C testtime
