/*
 * Telefónica Digital - Product Development and Innovation
 *
 * THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 *
 * Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
 * All rights reserved.
 */

/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_url_ClearVisitedURLs
#define _H_SAMSON_url_ClearVisitedURLs


#include <samson/module/samson.h>


/***********************************************************************
reduce ClearVisitedURLs
{
	in system.UInt url.ServerPathVector   # User(id) - ServerPathVector (suitable)
	in system.UInt url.ServerPathVector	  # User(id) - ServerPathVector (already visited)
	out system.UInt url.ServerPathVector  # User(id) - ServerPathVector (recommended)

	helpLine "Eliminate the URLs already visited from the list of possible recommendations"
}
************************************************************************/

namespace samson{
namespace url{


	class ClearVisitedURLs : public samson::Reduce
	{
		samson::system::UInt userId;
		ServerPathVector pathsSuitable;
		ServerPathVector pathsVisited;


	public:


		void run(  samson::KVSetStruct* inputs , samson::KVWriter *writer )
		{
			if (inputs[0].num_kvs == 0)
			{
				return; //We don't have any suitable recommendation
			}

			if (inputs[0].num_kvs != 1)
			{
				OLM_E(("We should have one and only one occurrence of users in recommended list. inputs[0].num_kvs: %d", inputs[0].num_kvs));
				return;
			}


			ServerPathVector pathsRecommended;

			userId.parse(inputs[0].kvs[0]->key);
			pathsSuitable.parse(inputs[0].kvs[0]->value);

			if (inputs[1].num_kvs == 0)
			{
				OLM_D(("We don't have any history for user: %d", userId.value));
				writer->emit(0, &userId, &pathsSuitable);
				return; //We don't have any suitable recommendation
			}

			if (inputs[1].num_kvs != 1)
			{
				OLM_E(("We should have only one occurrence of user's history. inputs[1].num_kvs: %d", inputs[1].num_kvs));
				writer->emit(0, &userId, &pathsSuitable);
				return; //We don't have any suitable recommendation
			}
			pathsVisited.parse(inputs[1].kvs[0]->value);

			for (int i = 0; (i < pathsSuitable.serverPath_length); i++)
			{
				if (pathsVisited.contains(&(pathsSuitable.serverPath[i])) == false)
				{
					pathsRecommended.serverPathAdd()->copyFrom(&(pathsSuitable.serverPath[i]));
				}
			}

			writer->emit(0, &userId, &pathsRecommended);
		}


	};


} // end of namespace samson
} // end of namespace url

#endif
