
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_url_exportUInt_ServerPath
#define _H_SAMSON_url_exportUInt_ServerPath


#include <samson/module/samson.h>


namespace samson{
namespace url{


	class exportUInt_ServerPath : public samson::ParserOut
	{
		samson::system::UInt key;
		ServerPath val;

	public:


		void run(KVSetStruct* inputs , TXTWriter *writer )
		{
#ifdef MAX_STR_LEN
#undef MAX_STR_LEN
#endif

#define MAX_STR_LEN 1024
			char output[MAX_STR_LEN];

			for (size_t i = 0; (i < inputs[0].num_kvs); i++)
			{
				key.parse(inputs[0].kvs[i]->key);
				val.parse(inputs[0].kvs[i]->value);

				snprintf(output, MAX_STR_LEN, "%lu|%lu|%s\n", key.value, val.server.value, val.path.value.c_str());

				writer->emit(output);
			}
		}


	};


} // end of namespace samson
} // end of namespace url

#endif
