
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_sna_light_extract_dyads
#define _H_SAMSON_sna_light_extract_dyads


#include <samson/samson.h>


namespace ss{
namespace sna_light{


	class extract_dyads : public ss::Script
	{

	public:




	};


} // end of namespace ss
} // end of namespace sna_light

#endif
