
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_sna_light_generate_single_clique
#define _H_SAMSON_sna_light_generate_single_clique


#include <samson/module/samson.h>


namespace samson{
namespace sna_light{


	class generate_single_clique : public samson::Generator
	{

	public:


		void run( samson::KVWriter *writer )
		{
		}


	};


} // end of namespace samson
} // end of namespace sna_light

#endif
