
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_sna_light_get_cliques_from_cliques_groups2
#define _H_SAMSON_sna_light_get_cliques_from_cliques_groups2


#include <samson/samson.h>


namespace ss{
namespace sna_light{


	class get_cliques_from_cliques_groups2 : public ss::Reduce
	{

	public:


		void run(  ss::KVSetStruct* inputs , ss::KVWriter *writer )
		{
		}


	};


} // end of namespace ss
} // end of namespace sna_light

#endif
