
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_sna_light_get_cliques_graph
#define _H_SAMSON_sna_light_get_cliques_graph


#include <samson/samson.h>


namespace ss{
namespace sna_light{


	class get_cliques_graph : public ss::Script
	{

	public:




	};


} // end of namespace ss
} // end of namespace sna_light

#endif
