
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_sna_light_metrics_calculate_metrics_reach_nodes
#define _H_SAMSON_sna_light_metrics_calculate_metrics_reach_nodes


#include <samson/samson.h>


namespace ss{
namespace sna_light{


	class metrics_calculate_metrics_reach_nodes : public ss::Reduce
	{

	public:


		void run(  ss::KVSetStruct* inputs , ss::KVWriter *writer )
		{
		}


	};


} // end of namespace ss
} // end of namespace sna_light

#endif
