
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_sna_light_metrics_graph_to_metrics_of_nodes
#define _H_SAMSON_sna_light_metrics_graph_to_metrics_of_nodes


#include <samson/module/samson.h>


namespace samson{
namespace sna_light{


	class metrics_graph_to_metrics_of_nodes : public samson::Script
	{

	public:




	};


} // end of namespace samson
} // end of namespace sna_light

#endif
