
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_sna_light_nodes_to_links
#define _H_SAMSON_sna_light_nodes_to_links


#include <samson/samson.h>


namespace ss{
namespace sna_light{


	class nodes_to_links : public ss::Map
	{

	public:


		void run(  ss::KVSetStruct* inputs , ss::KVWriter *writer )
		{
		}


	};


} // end of namespace ss
} // end of namespace sna_light

#endif
