
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_sna_light_parse_users
#define _H_SAMSON_sna_light_parse_users


#include <samson/samson.h>


namespace ss{
namespace sna_light{


	class parse_users : public ss::Parser
	{

	public:


		void run( char *data , size_t length , ss::KVWriter *writer )
		{
		}


	};


} // end of namespace ss
} // end of namespace sna_light

#endif
