
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_sna_light_parse_cliques2
#define _H_SAMSON_sna_light_parse_cliques2


#include <samson/samson.h>


namespace ss{
namespace sna_light{


	class parse_cliques2 : public ss::Script
	{

	public:




	};


} // end of namespace ss
} // end of namespace sna_light

#endif
