
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_sna_light_replace_callee_phone
#define _H_SAMSON_sna_light_replace_callee_phone


#include <samson/module/samson.h>


namespace samson{
namespace sna_light{


	class replace_callee_phone : public samson::Reduce
	{

	public:


		void run(  samson::KVSetStruct* inputs , samson::KVWriter *writer )
		{
		}


	};


} // end of namespace samson
} // end of namespace sna_light

#endif
