
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_sna_light_select_clique_links_to_be_removed
#define _H_SAMSON_sna_light_select_clique_links_to_be_removed


#include <samson/samson.h>


namespace ss{
namespace sna_light{


	class select_clique_links_to_be_removed : public ss::Reduce
	{

	public:


		void run(  ss::KVSetStruct* inputs , ss::KVWriter *writer )
		{
		}


	};


} // end of namespace ss
} // end of namespace sna_light

#endif
