
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_MOB_Levels
#define _H_SAMSON_MOB_Levels


#include <samson/modules/MOB/Levels_base.h>


namespace samson{
namespace MOB{


	class Levels : public Levels_base
	{
	};


} // end of namespace samson
} // end of namespace MOB

#endif
