
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_MOB_PhoneLoc
#define _H_SAMSON_MOB_PhoneLoc


#include <samson/modules/MOB/PhoneLoc_base.h>


namespace samson{
namespace MOB{


	class PhoneLoc : public PhoneLoc_base
	{
	};


} // end of namespace samson
} // end of namespace MOB

#endif
