
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_MOB_Place
#define _H_SAMSON_MOB_Place


#include <samson/modules/MOB/Place_base.h>


namespace samson{
namespace MOB{


	class Place : public Place_base
	{
	};


} // end of namespace samson
} // end of namespace MOB

#endif
