Module example
{
	title	"Example module to play with samson"
	author	"Andreu Urruela"
	version "0.1"
}


data example
{
	file Datas.h	

	system.UInt a;
	vector system.UInt b;
	system.Int32 c;
}


map map
{
	in system.UInt system.UInt
	out system.UInt system.UInt
	file ModuleImpl.cpp
}

generator generator
{
	out system.UInt system.UInt	
	file ModuleImpl.cpp
}

script script
{
	in base.UInt base.UInt2
	out base.UInt system.Void

	help
	{
		"An example of a script that creates two queues. This will no be a valid strings...just debugging"
	}

	code
	"
		add_queue pepe system.UInt system.UInt
		add_queue andreu system.UInt system.UInt
	"
}

script s2
{
	code
	"
		_example.script A B

	"
}