#include "/mnt/sda9/kzangeli/sb/samson/01/trunk/modules/example/Module.h"
/**
	This file has been autogenerated with samson_module.
	Please, do not modify directly
*/


extern "C" {
	ss::Module * moduleCreator( )
	{
		return new ss::example::Module();
	}
	std::string getSamsonVersion()
	{
		return SAMSON_VERSION;
	}
}
