/*
 * Telefónica Digital - Product Development and Innovation
 *
 * THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 *
 * Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
 * All rights reserved.
 */

/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_sort_export_sequence
#define _H_SAMSON_sort_export_sequence


#include <samson/module/samson.h>


namespace samson{
namespace sort{


	class export_sequence : public samson::ParserOut
	{
		samson::system::UInt number;

#ifdef MAX_STR_LEN
#undef MAX_STR_LEN
#endif

#define MAX_STR_LEN 64
			char output[MAX_STR_LEN];

	public:


		void run(KVSetStruct* inputs , TXTWriter *writer )
		{


			//OLM_T(LMT_User01, ("export_sequence: inputs[0].num_kvs:%lu", inputs[0].num_kvs));

            for (size_t i = 0; (i < inputs[0].num_kvs); ++i)
            {
                    number.parse( inputs[0].kvs[i]->key );
                    //OLM_T(LMT_User01, ("i:%ld, val:%ld", i, number.value));


                    snprintf(output, MAX_STR_LEN, "%lu\n", number.value);

                    writer->emit(output);
            }
		}


	};


} // end of namespace samson
} // end of namespace sort

#endif
