
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_system_parse_xml_documents
#define _H_SAMSON_system_parse_xml_documents


#include <samson/module/samson.h>
#include <samson/modules/system/Value.h>


namespace samson{
namespace system{


	class parse_xml_documents : public samson::Parser
	{

	public:


//  INFO_MODULE
// If interface changes and you do not recreate this file, you will have to update this information (and of course, the module file)
// Please, do not remove this comments, as it will be used to check consistency on module declaration
//
//  output: system.Value system.Value
//  
// helpLine: Parse xml documents and generate system.Values as maps
//  END_INFO_MODULE

		void init( samson::KVWriter *writer )
		{
		}

		void run( char *data , size_t length , samson::KVWriter *writer )
		{
		}

		void finish( samson::KVWriter *writer )
		{
		}



	};


} // end of namespace system
} // end of namespace samson

#endif
