#!/bin/bash



# #############################################################################
#
# samsonValgrindProcesses -
#
function samsonValgrindProcesses
{
	echo '------------------------ Samson Platform process list ------------------------'
	ps aux | egrep 'samsonWorker|samsonController|samsonSpawner' | grep -v '<defunct>' | grep -v egrep | grep valgrind | sort
	echo '------------------------------------------------------------------------------'
}



# #############################################################################
#
# looping ...
#
while /bin/true
do
	clear
	samsonValgrindProcesses
	sleep 0.5
done
