#!/bin/bash
#
# Script to remove samson from a system, in particular the 
# Bigdata cluster image. Designed to be used when testing 
# changes to the base image and the packages
aptitude -y remove samson samson-cdr samson-dev samson-docs samson-example samson-graph samson-mob2 samson-mobility samson-osn samson-passive-location samson-sna samson-sort samson-system samson-terasort  samson-tienda samson-txt samson-txt-md samson-url samson-urlbenchmark
# Clean the package cache, removing all downloaded packages
apt-get clean
# delete /var/samson since it does not get deleted when the packages are removed
rm -rf /var/samson
rm -rf /var/log/samson
