
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_url_ExpandCategoryHits
#define _H_SAMSON_url_ExpandCategoryHits


#include <samson/module/samson.h>

/*********************************************************************
map ExpandCategoryHits
{
	in system.UInt url.ServerPathVector # Category(id) - ServerPathVector
	out system.UInt url.CategoryPath    # Server(id) - CategoryPath

	helpLine "Transforms the key-values in order to make later the server decoding"
}
**********************************************************************/

namespace samson{
namespace url{


	class ExpandCategoryHits : public samson::Map
	{

	public:

		samson::system::UInt catId;
		samson::system::UInt serverId;
		CategoryPath catPath;
		ServerPathVector paths;

		void run(  samson::KVSetStruct* inputs , samson::KVWriter *writer )
		{


			for (size_t i = 0; (i < inputs[0].num_kvs); i++)
			{
				catId.parse(inputs[0].kvs[i]->key);
				paths.parse(inputs[0].kvs[i]->value);
				catPath.category = catId;
				for (int i = 0; (i < paths.serverPath_length); i++)
				{
					catPath.path = paths.serverPath[i].path;
					serverId = paths.serverPath[i].server;
					writer->emit(0, &serverId, &catPath);
				}
			}
		}
	};


} // end of namespace samson
} // end of namespace url

#endif
