
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_url_getServerCategory
#define _H_SAMSON_url_getServerCategory


#include <samson/samson.h>


namespace ss{
namespace url{


	class getServerCategory : public ss::Reduce
	{

	public:


		void run(  ss::KVSetStruct* inputs , ss::KVWriter *writer )
		{
		}


	};


} // end of namespace ss
} // end of namespace url

#endif
