
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_url_script_GeneratingFakes
#define _H_SAMSON_url_script_GeneratingFakes


#include <samson/samson.h>


namespace ss{
namespace url{


	class script_GeneratingFakes : public ss::Script
	{

	public:




	};


} // end of namespace ss
} // end of namespace url

#endif
