
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_simple_mobility_User
#define _H_SAMSON_simple_mobility_User


#include <samson/modules/simple_mobility/User_base.h>


namespace samson{
namespace simple_mobility{


	class User : public User_base
	{

	public:

	   void init()
	   {
		  // Init the position elememnt
		  position.set( 0 , 0 );

		  // Set length of the areas
		  areasSetLength(0);

		  // Set tracking to false
		  setTraking( false );
	   }

	   bool isTracking()
	   {
		  return (track.value != 0);
	   }
	   
	   void setTraking( bool p )
	   {
		  if ( p )
			 track.value = 1;
		  else
			 track.value = 0;
	   }


	};


} // end of namespace samson
} // end of namespace simple_mobility

#endif
