
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_OTTstream_Command
#define _H_SAMSON_OTTstream_Command


#include <samson/modules/OTTstream/Command_base.h>


namespace samson{
namespace OTTstream{


	class Command : public Command_base
	{
	};


} // end of namespace samson
} // end of namespace OTTstream

#endif
