
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_sna_compute_all_metric
#define _H_SAMSON_sna_compute_all_metric


#include <samson/module/samson.h>


namespace samson{
namespace sna{


	class compute_all_metric : public samson::Script
	{

	public:




	};


} // end of namespace samson
} // end of namespace sna

#endif
