/*
 * Telefónica Digital - Product Development and Innovation
 *
 * THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 *
 * Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
 * All rights reserved.
 */

/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_sna_spread_cliques_per_node
#define _H_SAMSON_sna_spread_cliques_per_node


#include <samson/module/samson.h>


namespace samson{
namespace sna{


	class spread_cliques_per_node : public samson::Map
	{

	public:


		void run(  samson::KVSetStruct* inputs , samson::KVWriter *writer )
		{
			Clique clique;
			samson::system::UInt nodeId;

			if ( inputs[0].num_kvs == 0)
				return;

			for (size_t i = 0  ; i < inputs[0].num_kvs ; i++)
			{
				clique.parse( inputs[0].kvs[i]->key );

				for (int j = 0 ; j < clique.nodes_length ; j++)
				{
					nodeId = clique.nodes[j];
					writer->emit(0, &nodeId, &clique);
				}
			}
		}


	};


} // end of namespace samson
} // end of namespace sna

#endif
