
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_snalight_acg_map_dup_cdrs
#define _H_SAMSON_snalight_acg_map_dup_cdrs


#include <samson/module/samson.h>
#include <stdint.h>


namespace samson{
namespace snalight{


	class acg_map_dup_cdrs : public samson::Map
	{

	public:


		void run(  samson::KVSetStruct* inputs , samson::KVWriter *writer )
		{
			samson::system::UInt phone;
			samson::snalight::CDR cdr;

			samson::system::UInt phone_rev;
			samson::snalight::CDR cdr_rev;

			for (uint64_t i=0  ; i< inputs[0].num_kvs ;++i)
			{
				phone.parse(inputs[0].kvs[i]->key);
				cdr.parse(inputs[0].kvs[i]->value);

				phone_rev = cdr.node;
				
				cdr_rev.copyFrom ( &cdr );
				cdr_rev.node = phone;
				cdr_rev.dir.value  = 1 - cdr.dir.value;

				writer->emit(0, &phone, &cdr);
				writer->emit(0, &phone_rev, &cdr_rev);
			}
		}
	};


} // end of namespace samson
} // end of namespace snalight

#endif
