
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_snalight_communities_unique_id_out
#define _H_SAMSON_snalight_communities_unique_id_out


#include <samson/module/samson.h>


namespace samson{
namespace snalight{


	class communities_unique_id_out : public samson::ParserOut
	{

	public:


		void run(KVSetStruct* inputs , TXTWriter *writer )
		{
		}


	};


} // end of namespace samson
} // end of namespace snalight

#endif
