
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_snalight_metrics_calculate_density_metric_cluster
#define _H_SAMSON_snalight_metrics_calculate_density_metric_cluster


#include <samson/module/samson.h>


namespace samson{
namespace snalight{


	class metrics_calculate_density_metric_cluster : public samson::Reduce
	{

	public:


		void run(  samson::KVSetStruct* inputs , samson::KVWriter *writer )
		{
		}


	};


} // end of namespace samson
} // end of namespace snalight

#endif
