/*
 * Telefónica Digital - Product Development and Innovation
 *
 * THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 *
 * Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
 * All rights reserved.
 */

/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_example_generator_error_timeout
#define _H_SAMSON_example_generator_error_timeout


#include <samson/module/samson.h>
#include <samson/modules/system/UInt.h>
#include <unistd.h>


namespace samson{
namespace example{


	class generator_error_timeout : public samson::Generator
	{

	public:


#ifdef INFO_COMMENT //Just to include a comment without conflicting anything
// If interface changes and you do not recreate this file, consider updating this information (and of course, the module file)

output: system.UInt system.UInt

helpLine: Generator that fails when executing for a timeout.
#endif // de INFO_COMMENT

		void init( samson::KVWriter *writer )
		{
		}

		void setup( int worker , int num_workers, int process , int num_processes )
		{
		}

		void run( samson::KVWriter *writer )
		{
		   // Timeout should cancel this job
		   while( true )
			  sleep(1);
		}

		void finish( samson::KVWriter *writer )
		{
		}



	};


} // end of namespace example
} // end of namespace samson

#endif
