
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_sna_compute_cliques_graph
#define _H_SAMSON_sna_compute_cliques_graph


#include <samson/module/samson.h>


namespace samson{
namespace sna{


	class compute_cliques_graph : public samson::Reduce
	{

	public:


		void run(  samson::KVSetStruct* inputs , samson::KVWriter *writer )
		{
			Clique clique;
			Clique_Node node_clique;
			Clique_Link clique_link;
			Link link;

			// Get the working clique (unique)
			clique.parse( inputs[0].kvs[0]->key );

			//Prepare the output vector with itself as reference
			node_clique.clique.copyFrom( &clique );

			node_clique.linksSetLength(0);
			for (size_t i = 0 ; i < inputs[1].num_kvs ; i++)
			{
				clique_link.parse( inputs[1].kvs[i]->value );
				node_clique.linksAdd()->copyFrom( &clique_link );
			}


			//Emit the computed graph
			writer->emit(0, &clique, &node_clique);

		}


	};


} // end of namespace samson
} // end of namespace sna

#endif
