
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_sna_get_graph_from_links2
#define _H_SAMSON_sna_get_graph_from_links2


#include <samson/module/samson.h>


namespace samson{
namespace sna{


	class get_graph_from_links2 : public samson::Reduce
	{

	public:


		void run(  samson::KVSetStruct* inputs , samson::KVWriter *writer )
		{
			samson::system::UInt nodeId ;
			Link link ;
			Node node ;

			  //Get the key
			  nodeId.parse(inputs[0].kvs[0]->key);
			  node.id = nodeId.value;   //Set the id of the output value

			  //Clean node
			  node.linksSetLength(0);

			  //Add the links form the "values"
			  for (int i = 0 ; i < inputs[0].num_kvs ; i++)
			  {
			    link.parse( inputs[0].kvs[i]->value );
			    node.linksAdd()->copyFrom( &link );
			  }

			  //No flags for the resulting graph (by default)
			  node.flags.value = Node::NODE_FLAG_NONE;

			  writer->emit(0, &nodeId, &node);

		}


	};


} // end of namespace samson
} // end of namespace sna

#endif
