
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_sna_metrics_graph_to_metrics_of_node_communities
#define _H_SAMSON_sna_metrics_graph_to_metrics_of_node_communities


#include <samson/module/samson.h>


namespace samson{
namespace sna{


	class metrics_graph_to_metrics_of_node_communities : public samson::Script
	{

	public:




	};


} // end of namespace samson
} // end of namespace sna

#endif
