
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_example_error
#define _H_SAMSON_example_error


#include <samson/Operation.h>
#include <samson/modules/system/UInt.h>

namespace ss{
namespace example{


	class error : public ss::Map
	{

	  ss::system::UInt key;
	  ss::system::UInt value;

	public:



		void run(  ss::KVSetStruct* inputs , ss::KVWriter *writer )
		{
		    for (int i = 0 ; i < inputs[0].num_kvs ; i++)
		    {
		      key.parse( inputs[0].kvs[i]->key );
		      value.parse( inputs[0].kvs[i]->value );

		      writer->emit(0,&key,&value);

		    }

		    int a = 0 ;
		    int b = 0; 
		    int c = a / b ; // this will clearly cause a run-time error
		  

		}


	};


} // end of namespace ss
} // end of namespace example

#endif
