
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_example_s2
#define _H_SAMSON_example_s2


#include <samson/Operation.h>


namespace ss{
namespace example{


	class s2 : public ss::Script
	{

	public:




	};


} // end of namespace ss
} // end of namespace example

#endif
