
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_snalight_Node_Communities
#define _H_SAMSON_snalight_Node_Communities


#include <samson/modules/snalight/Node_Communities_base.h>


namespace samson{
namespace snalight{


	class Node_Communities : public Node_Communities_base
	{
	};


} // end of namespace samson
} // end of namespace snalight

#endif
