
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_osn_bytemobile_req
#define _H_SAMSON_osn_bytemobile_req


#include <samson/Operation.h>


namespace ss{
namespace osn{


	class bytemobile_req : public ss::Script
	{

	public:




	};


} // end of namespace ss
} // end of namespace osn

#endif
