
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_osn_map_site_user
#define _H_SAMSON_osn_map_site_user


#include <samson/Operation.h>
#include <string>
#define DEBUG_FILES
#ifdef DEBUG_FILES
#include <iostream>
#include <fstream>
#endif /* de DEBUG_FILES */



namespace ss{
namespace osn{


	class map_site_user : public ss::Map
	{

	public:


		void run(  ss::KVSetStruct* inputs , ss::KVWriter *writer )
		{
			//ss::system::UInt64 msisdn;
			//ss::osn::URLConnection  connect;
			//ss::system::String key_out;
			//ss::system::UInt value_out;

			std::string user_agent = environment->get("osn.user_agent_query", "iphone");
			std::string domain = environment->get("osn.domain_query", "search.yahoo.com");

			const char *p_user_agent = user_agent.c_str();
			const char *p_domain = domain.c_str();

#define DEBUG_FILES
#ifdef DEBUG_FILES
                {
                std::string filename = "/tmp/map_site_user.log";
                std::ofstream fs(filename.c_str(), std::ios::app);
                fs << "Maps urls with domain: " << domain << " and user_agent: " << user_agent  << " for " << inputs[0].num_kvs << " logs " << std::endl;
                fs.close();
                }
#endif /* de DEBUG_FILES */
#undef DEBUG_FILES

			for (size_t i=0; (i < inputs[0].num_kvs); i++)
			{
				ss::system::UInt64 msisdn;
				ss::osn::URLConnection  connect;
				ss::system::String key_out;
				ss::system::UInt value_out;

				msisdn.parse(inputs[0].kvs[i]->key);
				connect.parse(inputs[0].kvs[i]->value);

				if ((strcasestr(connect.userAgent.value.c_str(), p_user_agent)) && (strstr(connect.url.url_host.value.c_str(), p_domain)))
				{
#ifdef DEBUG_FILES
                {
                std::string filename = "/tmp/map_site_user.log";
                std::ofstream fs(filename.c_str(), std::ios::app);
                fs << "Emit: " << connect.url.url_host.value << " and user_agent: " << connect.userAgent.value << std::endl;
                fs.close();
                }
#endif /* de DEBUG_FILES */
#undef DEBUG_FILES

					key_out = connect.url.url_host;

					value_out.value = 1;
					writer->emit(0, &key_out, &value_out);
					key_out.value.clear();
				}
#ifdef ELIMINADO
				else
				{
#define DEBUG_FILES
#ifdef DEBUG_FILES
                {
                std::string filename = "/tmp/map_site_user.log";
                std::ofstream fs(filename.c_str(), std::ios::app);
                fs << "Not: " << connect.url.url_host.value << " and user_agent: " << connect.userAgent.value << std::endl;
                fs.close();
                }
#endif /* de DEBUG_FILES */
#undef DEBUG_FILES
				}
#endif /* de ELIMINADO */

			}
			ss::system::UInt key_total;
			ss::system::UInt val_total;
			key_total.value = 1;
			val_total.value = inputs[0].num_kvs;
			writer->emit(1, &key_total, &val_total);
		}
	};


} // end of namespace ss
} // end of namespace osn

#endif
