
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_snalight_add_associated_nodes
#define _H_SAMSON_snalight_add_associated_nodes


#include <samson/module/samson.h>


namespace samson{
namespace snalight{


	class add_associated_nodes : public samson::Script
	{

	public:




	};


} // end of namespace samson
} // end of namespace snalight

#endif
