
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_snalight_gen_comm_clique
#define _H_SAMSON_snalight_gen_comm_clique


#include <samson/module/samson.h>


namespace samson{
namespace snalight{


	class gen_comm_clique : public samson::Map
	{

	public:


		void run(  samson::KVSetStruct* inputs , samson::KVWriter *writer )
		{
		}


	};


} // end of namespace samson
} // end of namespace snalight

#endif
