
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_shop_Transaction
#define _H_SAMSON_shop_Transaction


#include <samson/modules/shop/Transaction_base.h>


namespace samson{
namespace shop{


	class Transaction : public Transaction_base
	{

	};


} // end of namespace samson
} // end of namespace shop

#endif
