// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebLog.proto

package es.tid.ps.kpicalculation.data;

public final class WebLogPB {
  private WebLogPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class WebLog extends
      com.google.protobuf.GeneratedMessage {
    // Use WebLog.newBuilder() to construct.
    private WebLog() {
      initFields();
    }
    private WebLog(boolean noInit) {}
    
    private static final WebLog defaultInstance;
    public static WebLog getDefaultInstance() {
      return defaultInstance;
    }
    
    public WebLog getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return es.tid.ps.kpicalculation.data.WebLogPB.internal_static_kpicalculation_WebLog_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return es.tid.ps.kpicalculation.data.WebLogPB.internal_static_kpicalculation_WebLog_fieldAccessorTable;
    }
    
    // required string visitorId = 1;
    public static final int VISITORID_FIELD_NUMBER = 1;
    private boolean hasVisitorId;
    private java.lang.String visitorId_ = "";
    public boolean hasVisitorId() { return hasVisitorId; }
    public java.lang.String getVisitorId() { return visitorId_; }
    
    // required string fullUrl = 2;
    public static final int FULLURL_FIELD_NUMBER = 2;
    private boolean hasFullUrl;
    private java.lang.String fullUrl_ = "";
    public boolean hasFullUrl() { return hasFullUrl; }
    public java.lang.String getFullUrl() { return fullUrl_; }
    
    // required string date = 3;
    public static final int DATE_FIELD_NUMBER = 3;
    private boolean hasDate;
    private java.lang.String date_ = "";
    public boolean hasDate() { return hasDate; }
    public java.lang.String getDate() { return date_; }
    
    // required string httpStatus = 4;
    public static final int HTTPSTATUS_FIELD_NUMBER = 4;
    private boolean hasHttpStatus;
    private java.lang.String httpStatus_ = "";
    public boolean hasHttpStatus() { return hasHttpStatus; }
    public java.lang.String getHttpStatus() { return httpStatus_; }
    
    // required string mimeType = 5;
    public static final int MIMETYPE_FIELD_NUMBER = 5;
    private boolean hasMimeType;
    private java.lang.String mimeType_ = "";
    public boolean hasMimeType() { return hasMimeType; }
    public java.lang.String getMimeType() { return mimeType_; }
    
    // required string userAgent = 6;
    public static final int USERAGENT_FIELD_NUMBER = 6;
    private boolean hasUserAgent;
    private java.lang.String userAgent_ = "";
    public boolean hasUserAgent() { return hasUserAgent; }
    public java.lang.String getUserAgent() { return userAgent_; }
    
    // required string method = 7;
    public static final int METHOD_FIELD_NUMBER = 7;
    private boolean hasMethod;
    private java.lang.String method_ = "";
    public boolean hasMethod() { return hasMethod; }
    public java.lang.String getMethod() { return method_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasVisitorId) return false;
      if (!hasFullUrl) return false;
      if (!hasDate) return false;
      if (!hasHttpStatus) return false;
      if (!hasMimeType) return false;
      if (!hasUserAgent) return false;
      if (!hasMethod) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasVisitorId()) {
        output.writeString(1, getVisitorId());
      }
      if (hasFullUrl()) {
        output.writeString(2, getFullUrl());
      }
      if (hasDate()) {
        output.writeString(3, getDate());
      }
      if (hasHttpStatus()) {
        output.writeString(4, getHttpStatus());
      }
      if (hasMimeType()) {
        output.writeString(5, getMimeType());
      }
      if (hasUserAgent()) {
        output.writeString(6, getUserAgent());
      }
      if (hasMethod()) {
        output.writeString(7, getMethod());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasVisitorId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getVisitorId());
      }
      if (hasFullUrl()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getFullUrl());
      }
      if (hasDate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getDate());
      }
      if (hasHttpStatus()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getHttpStatus());
      }
      if (hasMimeType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getMimeType());
      }
      if (hasUserAgent()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getUserAgent());
      }
      if (hasMethod()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getMethod());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static es.tid.ps.kpicalculation.data.WebLogPB.WebLog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static es.tid.ps.kpicalculation.data.WebLogPB.WebLog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static es.tid.ps.kpicalculation.data.WebLogPB.WebLog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static es.tid.ps.kpicalculation.data.WebLogPB.WebLog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static es.tid.ps.kpicalculation.data.WebLogPB.WebLog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static es.tid.ps.kpicalculation.data.WebLogPB.WebLog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static es.tid.ps.kpicalculation.data.WebLogPB.WebLog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static es.tid.ps.kpicalculation.data.WebLogPB.WebLog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static es.tid.ps.kpicalculation.data.WebLogPB.WebLog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static es.tid.ps.kpicalculation.data.WebLogPB.WebLog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(es.tid.ps.kpicalculation.data.WebLogPB.WebLog prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private es.tid.ps.kpicalculation.data.WebLogPB.WebLog result;
      
      // Construct using es.tid.ps.kpicalculation.data.WebLogPB.WebLog.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new es.tid.ps.kpicalculation.data.WebLogPB.WebLog();
        return builder;
      }
      
      protected es.tid.ps.kpicalculation.data.WebLogPB.WebLog internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new es.tid.ps.kpicalculation.data.WebLogPB.WebLog();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return es.tid.ps.kpicalculation.data.WebLogPB.WebLog.getDescriptor();
      }
      
      public es.tid.ps.kpicalculation.data.WebLogPB.WebLog getDefaultInstanceForType() {
        return es.tid.ps.kpicalculation.data.WebLogPB.WebLog.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public es.tid.ps.kpicalculation.data.WebLogPB.WebLog build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private es.tid.ps.kpicalculation.data.WebLogPB.WebLog buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public es.tid.ps.kpicalculation.data.WebLogPB.WebLog buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        es.tid.ps.kpicalculation.data.WebLogPB.WebLog returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof es.tid.ps.kpicalculation.data.WebLogPB.WebLog) {
          return mergeFrom((es.tid.ps.kpicalculation.data.WebLogPB.WebLog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(es.tid.ps.kpicalculation.data.WebLogPB.WebLog other) {
        if (other == es.tid.ps.kpicalculation.data.WebLogPB.WebLog.getDefaultInstance()) return this;
        if (other.hasVisitorId()) {
          setVisitorId(other.getVisitorId());
        }
        if (other.hasFullUrl()) {
          setFullUrl(other.getFullUrl());
        }
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        if (other.hasHttpStatus()) {
          setHttpStatus(other.getHttpStatus());
        }
        if (other.hasMimeType()) {
          setMimeType(other.getMimeType());
        }
        if (other.hasUserAgent()) {
          setUserAgent(other.getUserAgent());
        }
        if (other.hasMethod()) {
          setMethod(other.getMethod());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setVisitorId(input.readString());
              break;
            }
            case 18: {
              setFullUrl(input.readString());
              break;
            }
            case 26: {
              setDate(input.readString());
              break;
            }
            case 34: {
              setHttpStatus(input.readString());
              break;
            }
            case 42: {
              setMimeType(input.readString());
              break;
            }
            case 50: {
              setUserAgent(input.readString());
              break;
            }
            case 58: {
              setMethod(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string visitorId = 1;
      public boolean hasVisitorId() {
        return result.hasVisitorId();
      }
      public java.lang.String getVisitorId() {
        return result.getVisitorId();
      }
      public Builder setVisitorId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasVisitorId = true;
        result.visitorId_ = value;
        return this;
      }
      public Builder clearVisitorId() {
        result.hasVisitorId = false;
        result.visitorId_ = getDefaultInstance().getVisitorId();
        return this;
      }
      
      // required string fullUrl = 2;
      public boolean hasFullUrl() {
        return result.hasFullUrl();
      }
      public java.lang.String getFullUrl() {
        return result.getFullUrl();
      }
      public Builder setFullUrl(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasFullUrl = true;
        result.fullUrl_ = value;
        return this;
      }
      public Builder clearFullUrl() {
        result.hasFullUrl = false;
        result.fullUrl_ = getDefaultInstance().getFullUrl();
        return this;
      }
      
      // required string date = 3;
      public boolean hasDate() {
        return result.hasDate();
      }
      public java.lang.String getDate() {
        return result.getDate();
      }
      public Builder setDate(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDate = true;
        result.date_ = value;
        return this;
      }
      public Builder clearDate() {
        result.hasDate = false;
        result.date_ = getDefaultInstance().getDate();
        return this;
      }
      
      // required string httpStatus = 4;
      public boolean hasHttpStatus() {
        return result.hasHttpStatus();
      }
      public java.lang.String getHttpStatus() {
        return result.getHttpStatus();
      }
      public Builder setHttpStatus(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasHttpStatus = true;
        result.httpStatus_ = value;
        return this;
      }
      public Builder clearHttpStatus() {
        result.hasHttpStatus = false;
        result.httpStatus_ = getDefaultInstance().getHttpStatus();
        return this;
      }
      
      // required string mimeType = 5;
      public boolean hasMimeType() {
        return result.hasMimeType();
      }
      public java.lang.String getMimeType() {
        return result.getMimeType();
      }
      public Builder setMimeType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMimeType = true;
        result.mimeType_ = value;
        return this;
      }
      public Builder clearMimeType() {
        result.hasMimeType = false;
        result.mimeType_ = getDefaultInstance().getMimeType();
        return this;
      }
      
      // required string userAgent = 6;
      public boolean hasUserAgent() {
        return result.hasUserAgent();
      }
      public java.lang.String getUserAgent() {
        return result.getUserAgent();
      }
      public Builder setUserAgent(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasUserAgent = true;
        result.userAgent_ = value;
        return this;
      }
      public Builder clearUserAgent() {
        result.hasUserAgent = false;
        result.userAgent_ = getDefaultInstance().getUserAgent();
        return this;
      }
      
      // required string method = 7;
      public boolean hasMethod() {
        return result.hasMethod();
      }
      public java.lang.String getMethod() {
        return result.getMethod();
      }
      public Builder setMethod(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMethod = true;
        result.method_ = value;
        return this;
      }
      public Builder clearMethod() {
        result.hasMethod = false;
        result.method_ = getDefaultInstance().getMethod();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:kpicalculation.WebLog)
    }
    
    static {
      defaultInstance = new WebLog(true);
      es.tid.ps.kpicalculation.data.WebLogPB.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:kpicalculation.WebLog)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_kpicalculation_WebLog_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_kpicalculation_WebLog_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014WebLog.proto\022\016kpicalculation\"\203\001\n\006WebLo" +
      "g\022\021\n\tvisitorId\030\001 \002(\t\022\017\n\007fullUrl\030\002 \002(\t\022\014\n" +
      "\004date\030\003 \002(\t\022\022\n\nhttpStatus\030\004 \002(\t\022\020\n\010mimeT" +
      "ype\030\005 \002(\t\022\021\n\tuserAgent\030\006 \002(\t\022\016\n\006method\030\007" +
      " \002(\tB)\n\035es.tid.ps.kpicalculation.dataB\010W" +
      "ebLogPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_kpicalculation_WebLog_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_kpicalculation_WebLog_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_kpicalculation_WebLog_descriptor,
              new java.lang.String[] { "VisitorId", "FullUrl", "Date", "HttpStatus", "MimeType", "UserAgent", "Method", },
              es.tid.ps.kpicalculation.data.WebLogPB.WebLog.class,
              es.tid.ps.kpicalculation.data.WebLogPB.WebLog.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
