
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_OTTstream_ActivityByService
#define _H_SAMSON_OTTstream_ActivityByService


#include <samson/modules/OTTstream/ActivityByService_base.h>

namespace samson{
namespace OTTstream{


	class ActivityByService : public ActivityByService_base
	{
	  public:
	        void Init()
	        {
	       // Initialize to a large initial number of users to avoid reallocating several times

#define INITIAL_NUMBER_OF_USERS 100000
	            // Preallocate a number of services...
	            user_activitySetLength(INITIAL_NUMBER_OF_USERS);
	            // ... but start from 0
	            user_activitySetLength(0);

	        }

	        void AddUser(samson::OTTstream::User user, samson::system::TimeUnix timestamp, int count)
	        {
	            samson::OTTstream::UserActivity *user_item = user_activityAdd();
	            user_item->user = user;
	            user_item->last_timestamp = timestamp;
	            user_item->count = count;
	        }
	};


} // end of namespace samson
} // end of namespace OTTstream

#endif
