
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_OTTstream_WebActivityByUser
#define _H_SAMSON_OTTstream_WebActivityByUser


#include <samson/modules/OTTstream/WebActivityByUser_base.h>


namespace samson{
namespace OTTstream{


	class WebActivityByUser : public WebActivityByUser_base
	{
	};


} // end of namespace samson
} // end of namespace OTTstream

#endif
