/*
 * Telefónica Digital - Product Development and Innovation
 *
 * THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 *
 * Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
 * All rights reserved.
 */

/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_OTTstream_WebCategoryHit
#define _H_SAMSON_OTTstream_WebCategoryHit


#include <samson/modules/OTTstream/WebCategoryHit_base.h>


namespace samson{
namespace OTTstream{


	class WebCategoryHit : public WebCategoryHit_base
	{
	};


} // end of namespace samson
} // end of namespace OTTstream

#endif
