
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_url_script_ServerCategoriesDistribution
#define _H_SAMSON_url_script_ServerCategoriesDistribution


#include <samson/module/samson.h>


namespace samson{
namespace url{


	class script_ServerCategoriesDistribution : public samson::Script
	{

	public:




	};


} // end of namespace samson
} // end of namespace url

#endif
