/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
 */

#ifndef _H_SAMSON_passive_location_dummy_output
#define _H_SAMSON_passive_location_dummy_output

#include <samson/module/samson.h>
#include <samson/modules/mobility/Record.h>
#include <samson/modules/system/UInt.h>

namespace samson {
namespace passive_location {

class dummy_output : public samson::ParserOut {

  public:

//  INFO_MODULE
// If interface changes and you do not recreate this file, you will have to update this information (and of course, the module file)
// Please, do not remove this comments, as it will be used to check consistency on module declaration
//
//  input: system.UInt mobility.Record  
//  
// helpLine: dummy parserOut to have access to the queue
//  END_INFO_MODULE

    void init(TXTWriter *writer) {
    }

    void run(KVSetStruct* inputs, TXTWriter *writer) {
    }

    void finish(TXTWriter *writer) {
    }

};

} // end of namespace passive_location
} // end of namespace samson

#endif
