
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_graph_compute_graph_from_links
#define _H_SAMSON_graph_compute_graph_from_links


#include <samson/module/samson.h>


namespace samson{
namespace graph{


	class compute_graph_from_links : public samson::Script
	{

	public:




	};


} // end of namespace samson
} // end of namespace graph

#endif
