
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_test_generator
#define _H_SAMSON_test_generator


#include <samson/samson.h>
#include <samson/modules/module_test/Integer.h>

namespace ss{
namespace module_test{


	class generator : public ss::Generator
	{

	public:

	  ss::module_test::Integer key,value;
	  

		void run( ss::KVWriter *writer )
		{

		  for ( int i = 0 ; i < 1000 ; i++)
		  {
		    key.value = i;
		    value.value = i*i;

      		    writer->emit( 0 , & key, & value);
		  }
		}


	};


} // end of namespace ss
} // end of namespace test

#endif
