
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_test_test_1
#define _H_SAMSON_test_test_1


#include <samson/samson.h>


namespace ss{
namespace test{


	class test_1 : public ss::Script
	{

	public:




	};


} // end of namespace ss
} // end of namespace test

#endif
