#! /bin/sh
### BEGIN INIT INFO
# Provides:          FastCGI servers for Django
# Required-Start:    networking
# Required-Stop:     networking
# Default-Start:     2 3 4 5
# Default-Stop:      S 0 1 6
# Short-Description: Start FastCGI servers with Django.
# Description:       Django, in order to operate with FastCGI, must be started
#                    in a very specific way with manage.py. This must be done
#                    for each DJango web server that has to run.
### END INIT INFO
#
# Author:  Guillermo Fernandez Castellanos
#          <guillermo.fernandez.castellanos AT gmail.com>.
#
# Version: @(#)fastcgi 0.1 11-Jan-2007 guillermo.fernandez.castellanos AT gmail.com
# Version: customized by 29-March-2012 by Sebastian Ortega <sortega@tid.es>
#

#### SERVER SPECIFIC CONFIGURATION
PIDFILE="/var/run/bdp_fe/django.pid"
BUILDOUT_BIN="/usr/local/cosmos-frontend/bin"
RUN_AS=bdp
#### DO NOT CHANGE ANYTHING AFTER THIS LINE!

set -e

PATH=$BUILDOUT_BIN:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="BDP Web Frontend"
NAME=$0
SCRIPTNAME=/etc/init.d/$NAME

#
#       Function that starts the daemon/service.
#
d_start()
{
    if [ -f $PIDFILE ]; then
        RUNNING=$(ps aux | grep -c `cat $PIDFILE`)
        if [ $RUNNING = '0' ]; then
            echo -n "already running"
        else
            su $RUN_AS -c $BUILDOUT_BIN/django.fcgi
        fi
    else
        su $RUN_AS -c $BUILDOUT_BIN/django.fcgi
    fi
}

#
#       Function that stops the daemon/service.
#
d_stop() {
    if [ -f $PIDFILE ]; then
        kill `cat -- $PIDFILE`
    else
        echo -n "not pidfile"
    fi
}

ACTION="$1"
case "$ACTION" in
    start)
        echo -n "Starting $DESC: $NAME "
        d_start
        echo "."
        ;;

    stop)
        echo -n "Stopping $DESC: $NAME "
        d_stop
        echo "."
        ;;

    restart|force-reload)
        echo -n "Restarting $DESC: $NAME "
        d_stop
        sleep 1
        d_start
        echo "."
        ;;

    *)
        echo "Usage: $NAME {start|stop|restart|force-reload}" >&2
        exit 3
        ;;
esac

exit 0
# vim:set et ts=4 sts=4:
