.TH SAMSON\-MODULETEMPLATE 7 2011-07-08 "Samson" "Samson Module Libraries"
.SH NAME
samson\-moduletemplate \- call data record processing
.SH DESCRIPTION
The samson moduletemplate library is a basic template for developing new modules. It contains:
  makefile
  CMakeLists.txt:    For explicit dependencies, developer must only chamge 'moduletemplate' 
                     with the name of the module.
  module:            In this template file, data types and operations to be implemented in 
                     the module are defined. One of the modules of the platform, samsonModuleParser,
                     takes this file as input and an empty skeleton to be filled by the developer.
                     In the section 'Programacion de nuevos modulos' of the document XXX, the syntax
                     of this file is described.

.SH SEE ALSO
.BR samson (1),
.BR samson-cdr (7),
.BR samson-example (7),
.BR samson-graph (7),
.BR samson-osn (7),
.BR samson-sna (7),
.BR samson-sort (7),
.BR samson-system (7),
.BR samson-terasort (7),
.BR samson-test (7),
.BR samson-txt (7),
.BR samson-urlbenchmark (7)
