.TH SAMSON 7 2011-07-08 "Samson" "Samson Module Libraries"
.SH NAME
samson \- big data platform
.SH DESCRIPTION
Samson is a platform developed for processing big information volumes (> 1GB daily) and acting as front-end for a DataWarehouse,
so this one had to deal with a reasonable amount of data.

.SH Samson Platform
Samson is a platform based on C++ for running map&reduce tasks in a distributed way, and reducing the input data flow.
The platform permits a distribute execution of implemented operations and also to add new operations.



.SH SEE ALSO
.BR samson-cdr (7),
.BR samson-example (7),
.BR samson-graph (7),
.BR samson-moduletemplate (7),
.BR samson-osn (7),
.BR samson-sna (7),
.BR samson-sort (7),
.BR samson-system (7),
.BR samson-terasort (7),
.BR samson-test (7),
.BR samson-txt (7),
.BR samson-urlbenchmark (7)
