.TH SAMSON\-EXAMPLE 7 2011-07-08 "Samson" "Samson Module Libraries"
.SH NAME
samson\-example \- 
.SH DESCRIPTION
The samson EXAMPLE library is an implementation merely to test functionalities of
the samson platform.

.SH DATA TYPES
  MyData (UInt a, UInt b)

.SH FUNCTIONS
  Generator   generator (out UInt-UInt)
  generator   generator2 (out UInt-UInt, out UInt-UInt)
  Parser      p (out UInt-UInt)
  ParserOut   select (in UInt-UInt)
  Map         map (in UInt-UInt, out UInt-UInt)
  Map         error (in UInt-UInt, out UInt-UInt)
  Reduce      reduce (in UInt-UInt, out UInt-UInt)
  Reduce      reduce2 (in UInt-UInt, in UInt-UInt, out UInt-UInt, out UInt-UInt)


.SH SCRIPTS
  test   -> map; map; reduce
  script -> add; add; generator
  s2     -> script

.SH SEE ALSO
.BR samson (1),
.BR samson-cdr (7),
.BR samson-graph (7),
.BR samson-moduletemplate (7),
.BR samson-osn (7),
.BR samson-sna (7),
.BR samson-sort (7),
.BR samson-system (7),
.BR samson-terasort (7),
.BR samson-test (7),
.BR samson-txt (7),
.BR samson-urlbenchmark (7)
