.TH SAMSON\-TERASORT 7 2011-07-08 "Samson" "Samson Module Libraries"
.SH NAME
samson\-terasort \- sort implementation adapted for terasort competition
.SH DESCRIPTION
The samson TERASORT library is an adaption of the module samson-sort(7) to
comply to the terasort competition.

.SH DATA TYPES
  Partition (ad hoc implementation)
  Record    (String keyf, String num_rec, String val_f)

.SH FUNCTIONS
  Parser            parse_file (out terasort.Partition terasort.Record)
  ParserOutReduce   reduce_and_export (in terasort.Partition terasort.Record)

.SH SCRIPTS

.SH SEE ALSO
.BR samson (1),
.BR samson-cdr (7),
.BR samson-example (7),
.BR samson-graph (7),
.BR samson-moduletemplate (7),
.BR samson-osn (7),
.BR samson-sna (7),
.BR samson-sort (7),
.BR samson-system (7),
.BR samson-test (7),
.BR samson-txt (7),
.BR samson-urlbenchmark (7)
