.TH SAMSON\-GRAPH 7 2011-07-08 "Samson" "Samson Module Libraries"
.SH NAME
samson\-graph \- graph calculation of CDR processing output
.SH DESCRIPTION
The samson GRAPH library calculates a graph, based on the information 
retrieved from CFR processing.

.SH DATA TYPES
  Link (Uint id, UInt weigth)
  Node (UInt id, vector Link links, Uint8 flags)
  NodeDist (UInt id, vector Link links, Uint distance)
  VectorNode (vector Node items)

.SH FUNCTIONS
  Generator  fake_graph (out UInt-Node)
  Parser     parse_links (out UInt-Node)
  ParserOut  select_graph (in UInt-Node)
  ParserOut  export_graph_distances (in UInt-NodeDist)
  Map        spread_links (in UInt2-UInt, out UInt-Link)
  Map        filter_graph_map (in UInt-Node, out UInt-Node)
  Map        map_select_node_to_compute_distance (in UInt-Node, out UInt-NodeDist)
  Map        map_send_distance_through_links (in UInt-NodeDist, out UInt-NodeDist, out UInt-UInt)
  Reduce     get_graph_from_links (in UInt-Link, out UInt-Node)
  Reduce     accumulate_links (in UInt2-Void, in UInt2-UInt, out UInt2-UInt)
  Reduce     add_extern_mark_to_graph (in UInt-Node, in UInt-User, out UInt-Node)
  Reduce     filter_graph_reduce (in UInt-Node, out UInt-Node)
  Reduce     red_get_min_distance (in UInt-NodeDist, in UInt-UInt, out UInt-NodeDist)

.SH SCRIPTS
  compute_graph                   -> cdr.spread_cdrs_to_links; 
                                     get_graph_from_links;
                                     add_extern_mark_to_graph;
                                     filter_graph_map;
                                     filter_graph_reduce

  compute_graph_O2                -> set;
                                     cdr.parse_cdrs;
                                     cdr.parse_users_O2UK;
                                     accumulate_cdrs_into_links;
                                     compute_graph_from_links;
                                     add_extern_mark_to_graph;
                                     filter_graph_map;
                                     filter_graph_reduce

  compute_graph_from_links        -> spread_links;
                                     get_graph_from_links_filter_graph

  filter_graph                    -> filter_graph_map;
                                     filter_map_reduce

  parse_graph                     -> parse_links;
                                     get_graph_from_links2

  accumulate_cdrs_into_links      -> cdr.spread_cdrs_to_links2;
                                     accumulate links

  compute_breadthfirst_algorithm  -> parse_links;
                                     map_select_node_to_compute_distance;
                                     map_send_distance_through_links;
                                     red_get_min_distance;
                                     map_send_distance_through_links;
                                     red_get_min_distance;
                                     ... ;
                                     map_send_distance_through_links;
                                     red_get_min_distance;
                                     export_graph_distances

.SH SEE ALSO
.BR samson (1),
.BR samson-cdr (7),
.BR samson-example (7),
.BR samson-moduletemplate (7),
.BR samson-osn (7),
.BR samson-sna (7),
.BR samson-sort (7),
.BR samson-system (7),
.BR samson-terasort (7),
.BR samson-test (7),
.BR samson-txt (7),
.BR samson-urlbenchmark (7)
