
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_mob_Levels
#define _H_SAMSON_mob_Levels


#include <samson/modules/mob/Levels_base.h>


namespace samson{
namespace mob{


	class Levels : public Levels_base
	{
	};


} // end of namespace samson
} // end of namespace mob

#endif
