
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_example_test
#define _H_SAMSON_example_test


#include <samson/module/samson.h>


namespace samson{
namespace example{


	class test : public samson::Script
	{

	public:




	};


} // end of namespace samson
} // end of namespace example

#endif
