
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_snalight_get_clique_links_with_nodes
#define _H_SAMSON_snalight_get_clique_links_with_nodes


#include <samson/module/samson.h>


namespace samson{
namespace snalight{


	class get_clique_links_with_nodes : public samson::Reduce
	{

	public:


		void run(  samson::KVSetStruct* inputs , samson::KVWriter *writer )
		{
		}


	};


} // end of namespace samson
} // end of namespace snalight

#endif
