
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_snalight_metrics_graph_to_metrics_of_communities
#define _H_SAMSON_snalight_metrics_graph_to_metrics_of_communities


#include <samson/module/samson.h>


namespace samson{
namespace snalight{


	class metrics_graph_to_metrics_of_communities : public samson::Script
	{

	public:




	};


} // end of namespace samson
} // end of namespace snalight

#endif
