/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Categories */

#ifndef _Included_Categories
#define _Included_Categories
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Categories
 * Method:    InitFromTermsInDomainFlatFile
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_Categories_InitFromTermsInDomainFlatFile
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     Categories
 * Method:    LoadCSDictionary
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_Categories_LoadCSDictionary
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     Categories
 * Method:    ApplyDictionaryUsingUrl
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_Categories_ApplyDictionaryUsingUrl
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
