
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_url_UserPath
#define _H_SAMSON_url_UserPath


#include <samson/modules/url/UserPath_base.h>


namespace samson{
namespace url{


	class UserPath : public UserPath_base
	{
	};


} // end of namespace samson
} // end of namespace url

#endif
