
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_cdr_User
#define _H_SAMSON_cdr_User


#include <samson/modules/cdr/User_base.h>


namespace ss{
namespace cdr{


	class User : public User_base
	{
	};


} // end of namespace ss
} // end of namespace cdr

#endif
