
/**
 File autogenerated with samsonModuleParser, please do not edit
*/

#ifndef _H_SAMSON_sna_light_Link_Edges_BASE
#define _H_SAMSON_sna_light_Link_Edges_BASE


#include <samson/modules/system/UInt.h>


namespace samson{
namespace sna_light{


	class Link_Edges_base : public samson::DataInstance{

	public:
	::samson::system::UInt phoneA;
	::samson::system::UInt phoneB;

	Link_Edges_base() : samson::DataInstance(){
	}

	~Link_Edges_base() {
	}

	int parse(char *data){
		int offset=0;
		offset += phoneA.parse(data+offset);
		offset += phoneB.parse(data+offset);
		return offset;
	}

	int serialize(char *data){
		int offset=0;
		offset += phoneA.serialize(data+offset);
		offset += phoneB.serialize(data+offset);
		return offset;
	}

	static inline int size(char *data){
		int offset=0;
		offset += ::samson::system::UInt::size(data+offset);
		offset += ::samson::system::UInt::size(data+offset);
		return offset;
	}

	int hash(int max_num_partitions){
		return phoneA.hash(max_num_partitions);
	}

	inline static int compare(char * data1 , char *data2 , size_t *offset1 , size_t *offset2 ){
		{ // comparing phoneA
			int tmp = ::samson::system::UInt::compare(data1,data2,offset1 , offset2);
			if( tmp != 0) return tmp;
		}
		{ // comparing phoneB
			int tmp = ::samson::system::UInt::compare(data1,data2,offset1 , offset2);
			if( tmp != 0) return tmp;
		}
		return 0; //If everything is equal
	}

	inline static int compare( char* data1 , char* data2 )
	{
		size_t offset_1=0;
		size_t offset_2=0;
		return compare( data1 , data2 , &offset_1 , &offset_2 );
	}

	void copyFrom( Link_Edges_base *other ){
		phoneA.copyFrom(&other->phoneA);
		phoneB.copyFrom(&other->phoneB);
	};

	std::string str(){
		std::ostringstream o;
		o << phoneA.str();

		o<<" ";
		o << phoneB.str();

		o<<" ";
		return o.str();
	}

	}; //class Link_Edges_base

} // end of namespace samson
} // end of namespace sna_light

#endif
