
/**
 File autogenerated with samsonModuleParser, please do not edit
*/

#ifndef _H_SAMSON_sna_light_Metric_BASE
#define _H_SAMSON_sna_light_Metric_BASE


#include <samson/modules/system/UInt.h>


namespace ss{
namespace sna_light{


	class Metric_base : public ss::DataInstance{

	public:
	::ss::system::UInt id;
	::ss::system::UInt links_count;
	::ss::system::UInt strong_links_count;
	::ss::system::UInt strong_links_sum;
	::ss::system::UInt weak_links_count;
	::ss::system::UInt weak_links_sum;
	::ss::system::UInt strong_links_comp_count;
	::ss::system::UInt weak_links_comp_count;

	Metric_base() : ss::DataInstance(){
	}

	~Metric_base() {
	}

	int parse(char *data){
		int offset=0;
		offset += id.parse(data+offset);
		offset += links_count.parse(data+offset);
		offset += strong_links_count.parse(data+offset);
		offset += strong_links_sum.parse(data+offset);
		offset += weak_links_count.parse(data+offset);
		offset += weak_links_sum.parse(data+offset);
		offset += strong_links_comp_count.parse(data+offset);
		offset += weak_links_comp_count.parse(data+offset);
		return offset;
	}

	int serialize(char *data){
		int offset=0;
		offset += id.serialize(data+offset);
		offset += links_count.serialize(data+offset);
		offset += strong_links_count.serialize(data+offset);
		offset += strong_links_sum.serialize(data+offset);
		offset += weak_links_count.serialize(data+offset);
		offset += weak_links_sum.serialize(data+offset);
		offset += strong_links_comp_count.serialize(data+offset);
		offset += weak_links_comp_count.serialize(data+offset);
		return offset;
	}

	static inline int size(char *data){
		int offset=0;
		offset += ::ss::system::UInt::size(data+offset);
		offset += ::ss::system::UInt::size(data+offset);
		offset += ::ss::system::UInt::size(data+offset);
		offset += ::ss::system::UInt::size(data+offset);
		offset += ::ss::system::UInt::size(data+offset);
		offset += ::ss::system::UInt::size(data+offset);
		offset += ::ss::system::UInt::size(data+offset);
		offset += ::ss::system::UInt::size(data+offset);
		return offset;
	}

	int hash(int max_num_partitions){
		return id.hash(max_num_partitions);
	}

	inline static int compare(char * data1 , char *data2 , size_t *offset1 , size_t *offset2 ){
		{ // comparing id
			int tmp = ::ss::system::UInt::compare(data1,data2,offset1 , offset2);
			if( tmp != 0) return tmp;
		}
		{ // comparing links_count
			int tmp = ::ss::system::UInt::compare(data1,data2,offset1 , offset2);
			if( tmp != 0) return tmp;
		}
		{ // comparing strong_links_count
			int tmp = ::ss::system::UInt::compare(data1,data2,offset1 , offset2);
			if( tmp != 0) return tmp;
		}
		{ // comparing strong_links_sum
			int tmp = ::ss::system::UInt::compare(data1,data2,offset1 , offset2);
			if( tmp != 0) return tmp;
		}
		{ // comparing weak_links_count
			int tmp = ::ss::system::UInt::compare(data1,data2,offset1 , offset2);
			if( tmp != 0) return tmp;
		}
		{ // comparing weak_links_sum
			int tmp = ::ss::system::UInt::compare(data1,data2,offset1 , offset2);
			if( tmp != 0) return tmp;
		}
		{ // comparing strong_links_comp_count
			int tmp = ::ss::system::UInt::compare(data1,data2,offset1 , offset2);
			if( tmp != 0) return tmp;
		}
		{ // comparing weak_links_comp_count
			int tmp = ::ss::system::UInt::compare(data1,data2,offset1 , offset2);
			if( tmp != 0) return tmp;
		}
		return 0; //If everything is equal
	}

	inline static int compare( char* data1 , char* data2 )
	{
		size_t offset_1=0;
		size_t offset_2=0;
		return compare( data1 , data2 , &offset_1 , &offset_2 );
	}

	void copyFrom( Metric_base *other ){
		id.copyFrom(&other->id);
		links_count.copyFrom(&other->links_count);
		strong_links_count.copyFrom(&other->strong_links_count);
		strong_links_sum.copyFrom(&other->strong_links_sum);
		weak_links_count.copyFrom(&other->weak_links_count);
		weak_links_sum.copyFrom(&other->weak_links_sum);
		strong_links_comp_count.copyFrom(&other->strong_links_comp_count);
		weak_links_comp_count.copyFrom(&other->weak_links_comp_count);
	};

	std::string str(){
		std::ostringstream o;
		o << id.str();

		o<<" ";
		o << links_count.str();

		o<<" ";
		o << strong_links_count.str();

		o<<" ";
		o << strong_links_sum.str();

		o<<" ";
		o << weak_links_count.str();

		o<<" ";
		o << weak_links_sum.str();

		o<<" ";
		o << strong_links_comp_count.str();

		o<<" ";
		o << weak_links_comp_count.str();

		o<<" ";
		return o.str();
	}

	}; //class Metric_base

} // end of namespace ss
} // end of namespace sna_light

#endif
