
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_sna_light_Metric_Node_In_Comm
#define _H_SAMSON_sna_light_Metric_Node_In_Comm


#include <samson/modules/sna_light/Metric_Node_In_Comm_base.h>


namespace samson{
namespace sna_light{


	class Metric_Node_In_Comm : public Metric_Node_In_Comm_base
	{
	};


} // end of namespace samson
} // end of namespace sna_light

#endif
