
/**
 File autogenerated with samsonModuleParser, please do not edit
*/

#ifndef _H_SAMSON_sna_light_Metric_Cluster_BASE
#define _H_SAMSON_sna_light_Metric_Cluster_BASE


#include <samson/modules/system/UInt.h>


namespace ss{
namespace sna_light{


	class Metric_Cluster_base : public ss::DataInstance{

	public:
	::ss::system::UInt node_id;
	::ss::system::UInt cluster_coef;

	Metric_Cluster_base() : ss::DataInstance(){
	}

	~Metric_Cluster_base() {
	}

	int parse(char *data){
		int offset=0;
		offset += node_id.parse(data+offset);
		offset += cluster_coef.parse(data+offset);
		return offset;
	}

	int serialize(char *data){
		int offset=0;
		offset += node_id.serialize(data+offset);
		offset += cluster_coef.serialize(data+offset);
		return offset;
	}

	static inline int size(char *data){
		int offset=0;
		offset += ::ss::system::UInt::size(data+offset);
		offset += ::ss::system::UInt::size(data+offset);
		return offset;
	}

	int hash(int max_num_partitions){
		return node_id.hash(max_num_partitions);
	}

	inline static int compare(char * data1 , char *data2 , size_t *offset1 , size_t *offset2 ){
		{ // comparing node_id
			int tmp = ::ss::system::UInt::compare(data1,data2,offset1 , offset2);
			if( tmp != 0) return tmp;
		}
		{ // comparing cluster_coef
			int tmp = ::ss::system::UInt::compare(data1,data2,offset1 , offset2);
			if( tmp != 0) return tmp;
		}
		return 0; //If everything is equal
	}

	inline static int compare( char* data1 , char* data2 )
	{
		size_t offset_1=0;
		size_t offset_2=0;
		return compare( data1 , data2 , &offset_1 , &offset_2 );
	}

	void copyFrom( Metric_Cluster_base *other ){
		node_id.copyFrom(&other->node_id);
		cluster_coef.copyFrom(&other->cluster_coef);
	};

	std::string str(){
		std::ostringstream o;
		o << node_id.str();

		o<<" ";
		o << cluster_coef.str();

		o<<" ";
		return o.str();
	}

	}; //class Metric_Cluster_base

} // end of namespace ss
} // end of namespace sna_light

#endif
