
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_sna_light_Vector_Clique_Node
#define _H_SAMSON_sna_light_Vector_Clique_Node


#include <samson/modules/sna_light/Vector_Clique_Node_base.h>


namespace ss{
namespace sna_light{


	class Vector_Clique_Node : public Vector_Clique_Node_base
	{
	};


} // end of namespace ss
} // end of namespace sna_light

#endif
