
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_sna_light_VectorClique_Node
#define _H_SAMSON_sna_light_VectorClique_Node


#include <samson/modules/sna_light/VectorClique_Node_base.h>


namespace ss{
namespace sna_light{


	class VectorClique_Node : public VectorClique_Node_base
	{
	};


} // end of namespace ss
} // end of namespace sna_light

#endif
