
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_cdr_mobCdr
#define _H_SAMSON_cdr_mobCdr


#include <samson/modules/cdr/mobCdr_base.h>


namespace samson{
namespace cdr{


	class mobCdr : public mobCdr_base
	{
	};


} // end of namespace samson
} // end of namespace cdr

#endif
