
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
 */

#ifndef _H_SAMSON_mob2_vector_get_ncoms_nodedayhour
#define _H_SAMSON_mob2_vector_get_ncoms_nodedayhour


#include <samson/module/samson.h>
#include <samson/modules/mob2/Node_Bts.h>
#include <samson/modules/mob2/TwoInt.h>
#include <samson/modules/system/Void.h>



namespace samson{
namespace mob2{


class vector_get_ncoms_nodedayhour : public samson::Reduce
{
	//Inputs
	Node_Bts noddayhour;
	//Outputs
	Node_Bts nodbtsday;
	TwoInt hour_comms;       // num1: hour   num2:ncoms

public:


#ifdef INFO_COMMENT //Just to include a comment without conflicting anything
	// If interface changes and you do not recreate this file, consider updating this information (and of course, the module file)

	input: mob2.Node_Bts system.Void
	output: mob2.Node_Bts mob2.TwoInt

	extendedHelp: 		Get number of comms by node, day and hour

#endif // de INFO_COMMENT

	void init(samson::KVWriter *writer )
	{
	}

	void run(  samson::KVSetStruct* inputs , samson::KVWriter *writer )
	{
		noddayhour.parse(inputs[0].kvs[0]->key);
		nodbtsday.copyFrom(&noddayhour);
		nodbtsday.range.value = 0;
		hour_comms.num1.value = noddayhour.range.value;
		hour_comms.num2.value = inputs[0].num_kvs;

		writer->emit(0, &nodbtsday,&hour_comms);

	}

	void finish(samson::KVWriter *writer )
	{
	}



};


} // end of namespace mob2
} // end of namespace samson

#endif
