
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_mobility_fake_records
#define _H_SAMSON_mobility_fake_records


#include <samson/module/samson.h>
#include <samson/modules/mobility/Record.h>
#include <samson/modules/system/UInt.h>


namespace samson{
namespace mobility{


	class fake_records : public samson::Generator
	{

	public:


#ifdef INFO_COMMENT //Just to include a comment without conflicting anything
// If interface changes and you do not recreate this file, consider updating this information (and of course, the module file)

output: system.UInt mobility.Record

helpLine: Fake generator to have some mobility.Record items  for testing
#endif // de INFO_COMMENT

		void init( samson::KVWriter *writer )
		{
		}

		void setup( int worker , int num_workers, int process , int num_processes )
		{
		}

		void run( samson::KVWriter *writer )
		{
		}

		void finish( samson::KVWriter *writer )
		{
		}



	};


} // end of namespace mobility
} // end of namespace samson

#endif
