
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_c4_Info
#define _H_SAMSON_c4_Info


#include <samson/modules/c4/Info_base.h>
#include "extra/c4/Board.h"

namespace samson{
namespace c4{


	class Info : public Info_base
	{

	public:

	   Info()
	   {
		  reset();
	   }

	   void reset()
	   {
		  // Vector of winners in each position
		  movementSetLength(7);
		  for ( int i = 0 ; i < 7 ; i++ )
			 movement[i].value = 10; // Unknown
		  boardsSetLength(0);
	   }

	   std::string letter( int value )
	   {
		  if( value  == C4_WHITE )
			 return "W";
		  if( value  == C4_BLACK )
			 return "B";
		  if( value  == C4_DRAW )
			 return "D";
		  return "?";
	   }

	   std::string str()
	   {
		  std::ostringstream output;
		  
		  output << "Winner: " << letter( winner.value ) << " ";

		  output << "Movements: ";
		  for ( int i = 0 ; i < 7 ; i++ )
			 output << letter( movement[i].value  );

		  if( boards_length > 0 )
			 output << " (" << boards_length << " pending boards)";

		  return output.str();

	   }

	   
	};


} // end of namespace samson
} // end of namespace c4

#endif
