
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_sort_random_sequence_generator_common_key
#define _H_SAMSON_sort_random_sequence_generator_common_key


#include <samson/samson.h>


namespace ss{
namespace sort{


	class random_sequence_generator_common_key : public ss::Generator
	{

	public:


		void run( ss::KVWriter *writer )
		{
            size_t num_samples = environment->getSizeT( "test.number_of_samples", 1000000000);

            ss::system::UInt val;
            ss::system::UInt8 key;
            ss::system::Void dummy;

            key.value = 1;

            for (size_t i = 0; (i < num_samples); i++)
            {
                    val = rand();

                    writer->emit(0, &key, &val);
            }
		}


	};


} // end of namespace ss
} // end of namespace sort

#endif
