
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_mob2_cluster_spread_nodelbl_poilbl
#define _H_SAMSON_mob2_cluster_spread_nodelbl_poilbl


#include <samson/module/samson.h>
#include <samson/modules/mob2/Poi.h>
#include <samson/modules/mob2/TwoInt.h>
#include <samson/modules/system/Void.h>


namespace samson{
namespace mob2{


	class cluster_spread_nodelbl_poilbl : public samson::Map
	{
		//Inputs
		Poi poiInfo;
		//Outputs
		TwoInt nodlbl_poilbl; // num1: Node label	num2: Poi label
		samson::system::Void mr_void;


	public:


#ifdef INFO_COMMENT //Just to include a comment without conflicting anything
// If interface changes and you do not recreate this file, consider updating this information (and of course, the module file)

input: mob2.TwoInt mob2.Poi  
output: mob2.TwoInt system.Void

extendedHelp: 		Spread points of interest by client label and poi label

#endif // de INFO_COMMENT

		void init(samson::KVWriter *writer )
		{
		}

		void run(  samson::KVSetStruct* inputs , samson::KVWriter *writer )
		{

			for(uint64_t i=0; i<inputs[0].num_kvs; i++)
			{
				poiInfo.parse(inputs[0].kvs[i]->value);

				if ((poiInfo.confidentnode.value == 1) && (poiInfo.confidentnodebts.value == 1))
				{
					nodlbl_poilbl.num1.value = poiInfo.labelnode.value;
					nodlbl_poilbl.num2.value = poiInfo.labelnodebts.value;
					writer->emit(0, &nodlbl_poilbl,&mr_void);
				}
			}
		}

		void finish(samson::KVWriter *writer )
		{
		}



	};


} // end of namespace mob2
} // end of namespace samson

#endif
