
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_mob2_itin_count_ranges
#define _H_SAMSON_mob2_itin_count_ranges


#include <samson/module/samson.h>
#include <samson/modules/mob2/ItinRange.h>
#include <samson/modules/mob2/TwoInt.h>
#include <samson/modules/system/Void.h>



namespace samson{
namespace mob2{


	class itin_count_ranges : public samson::Reduce
	{
        //Inputs
        ItinRange moveRange;
        //Outputs
        TwoInt wday_count;

	public:


#ifdef INFO_COMMENT //Just to include a comment without conflicting anything
// If interface changes and you do not recreate this file, consider updating this information (and of course, the module file)

input: mob2.ItinRange system.Void  
output: mob2.ItinRange mob2.TwoInt

extendedHelp: 		Count num of movements in a range

#endif // de INFO_COMMENT

		void init(samson::KVWriter *writer )
		{
		}

		void run(  samson::KVSetStruct* inputs , samson::KVWriter *writer )
		{
        moveRange.parse(inputs[0].kvs[0]->key);
        wday_count.num1.value = moveRange.group.value;
        wday_count.num2.value = inputs[0].num_kvs;
        moveRange.group.value = 0;

        writer->emit(0, &moveRange,&wday_count);

		}

		void finish(samson::KVWriter *writer )
		{
		}



	};


} // end of namespace mob2
} // end of namespace samson

#endif
