
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_testcomparefunctions_Call
#define _H_SAMSON_testcomparefunctions_Call


#include <samson/modules/testcomparefunctions/Call_base.h>


namespace samson{
namespace testcomparefunctions{


	class Call : public Call_base
	{
	};


} // end of namespace samson
} // end of namespace testcomparefunctions

#endif
