#!/bin/bash
# Script to install SAMSON on ubuntu at boot time
# Place in /usr/local/sbin and edit /etc/rc.local so it gets
# called on startup.
# 
# See if SAMSON is already installed. If not, then install else
# do nothing.
install_status=`aptitude search samson | grep " samson " | awk '{ print $1 }'`
if [ "${install_status}" == "p" ];
then
    # Check to see if we can resolve the repository address
    dns_status=`host samson09.hi.inet>/dev/null;echo $?`
    while [ ${dns_status} -ne 0 ]; do
       echo "Waiting for DNS to come online"
       sleep 10
       dns_status=`host samson09.hi.inet>/dev/null;echo $?`
    done

    echo Installing Samson
    # Update the system cache in case there have been package changes
    aptitude update
    # Install
    # -y = say yes to all prompts
    # --allow-untrusted = since our packages are unsigned the default 
    #                behaviour is to not install, this flag by passes the check
    aptitude install -y  --allow-untrusted  samson samson-cdr samson-docs samson-example samson-graph samson-mob2 samson-mobility samson-osn samson-passive-location samson-sna samson-sort samson-system samson-terasort  samson-tienda samson-txt samson-txt-md samson-url samson-urlbenchmark
fi
