#!/bin/bash
#
# Checking command line options
#
if [ "$#" != 3 ]
then
	echo 'samsonRpm: Bad parameters'
	echo 'Usage: samsonRpm <Module name> <Version (e.g. 0.5)> <Release (e.g. 3)>'
	exit 1
fi

if [ -z "${SAMSON_HOME}"]; then 
   SAMSON_HOME=/opt/samson
fi

#
# Using command line options
#
module=$1
version=$2
release=$3



#
# Help variables
#
vr=$version.$release
tarfile=samson-$module-$version.tar.gz
specfile=samson-$module-$vr.spec
rdir=samson-$module-$version
BUILD_ROOT=$(pwd)
PACKAGE_DIR=${BUILD_ROOT}/rpm/scratch/$rdir

# Help functions

# Generate a list of module dependencies needed to install this module
dependencylist()
{
    echo -n "Requires: samson = $version, samson-devel = $version" >> rpm_module_list.$$
    # package_deps contains a list of external dependencies, e.g. mongodb needed
    # to ensure the correct functioning of the module
    if [ -f package_deps ]; then
        for needed_module in `cat package_deps`
        do
            echo -n ", $needed_module" >> deb_module_list.$$
        done
    fi
    if [ -f depends.txt ]; then
        for needed_module in `cat depends.txt`
        do
            echo -n ", $needed_module = $version" >> rpm_module_list.$$
        done
    fi
    cat rpm_module_list.$$
    rm rpm_module_list.$$
}


#
# Preparing HOME directory for RPM
#
echo "%_topdir $BUILD_ROOT/rpm" > ~/.rpmmacros
echo "%_unpackaged_files_terminate_build      0" >> ~/.rpmmacros

if [ ! -d $BUILD_ROOT/rpm ];
then
    mkdir -p $BUILD_ROOT/rpm/{SOURCES,SPECS,BUILD,SRPMS,BUILDROOT}
fi

#
# Creating link for 'compiled stuff' ...
#
arch=$(uname -p)
ln -s $BUILD_ROOT/rpm/BUILD/samson-$module-$version $BUILD_ROOT/rpm/BUILDROOT/samson-$module-$version-$release.$arch



#
# Creating the SPEC file
#
echo "Summary:   Samson $module module"                       > $BUILD_ROOT/rpm/SPECS/$specfile
echo "Name:      samson-$module"                             >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "Version:   " $version                                  >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "Release:   " $release                                  >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "License:   commercial"                                 >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "Group:     Applications/Engineering"                   >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "Source:    http://www.tid.es/samson-$module-$version.tar.gz"   >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "BuildRoot: /var/tmp/%{name}-buildroot"                 >> $BUILD_ROOT/rpm/SPECS/$specfile
dependencylist                                               >> $BUILD_ROOT/rpm/SPECS/$specfile
echo                                                         >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%description"                                          >> $BUILD_ROOT/rpm/SPECS/$specfile
# TODO - pull description in from a flat file
echo "Samson module $module"                                 >> $BUILD_ROOT/rpm/SPECS/$specfile
echo                                                         >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%prep"                                                 >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%setup"                                                >> $BUILD_ROOT/rpm/SPECS/$specfile
echo                                                         >> $BUILD_ROOT/rpm/SPECS/$specfile
#echo "%install"                                              >> $BUILD_ROOT/rpm/SPECS/$specfile
echo                                                         >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%clean"                                                >> $BUILD_ROOT/rpm/SPECS/$specfile
echo                                                         >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%files"                                                >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%defattr(-, samson, samson, -)"                        >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "/opt/samson/modules/lib$module.so"                     >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "/opt/samson/include/samson/modules/$module/"'*.h'      >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%changelog"                                            >> $BUILD_ROOT/rpm/SPECS/$specfile
echo                                                         >> $BUILD_ROOT/rpm/SPECS/$specfile



#
# Preparing the directory with the RPM contents
#
rm -rf $PACKAGE_DIR
mkdir -p $PACKAGE_DIR/opt/samson/include/samson/modules/$module
mkdir -p $PACKAGE_DIR/opt/samson/modules
cp $SAMSON_HOME/include/samson/modules/$module/*.h   $PACKAGE_DIR/opt/samson/include/samson/modules/$module/
cp $SAMSON_HOME/modules/lib$module.so               $PACKAGE_DIR/opt/samson/modules/


#
# Create the tar file
cd $PACKAGE_DIR/..
tar cvfz $tarfile $rdir 
mv $tarfile $BUILD_ROOT/rpm/SOURCES


#
# And finally, create the RPM
#
cd $BUILD_ROOT/rpm/SPECS
rpmbuild -bb $specfile
if [ ! -d $BUILD_ROOT/package/rpm/ ];
then
    mkdir -p $BUILD_ROOT/package/rpm
fi
mv $BUILD_ROOT/rpm/RPMS/$arch/samson-$module-$version-$release.$arch.rpm $BUILD_ROOT/../../package/rpm/
