#!/bin/sh -x
#
# Checking command line options
#
if [ "$#" != 2 ];
then
	echo 'samsonDebDev: Bad parameters'
	echo 'Usage: samsonDebDev <Version (e.g. 0.5)> <Release (e.g. 3)>'
	exit 1
fi

if [ -z "${SAMSON_HOME}" ]; then
	SAMSON_HOME=/opt/samson
fi

#
# Using command line options
#
version=$1
release=$2



#
# Help variables
#
arch=$(dpkg --print-architecture)
package_name=samson-dev
BUILD_ROOT=$(pwd)

#
# Populating debian
#
if [ -d debian ]; then
    rm -rf debian
fi

mkdir -p debian/DEBIAN
# Create the base structure needed
mkdir -p debian/opt/samson/include/samson/module
mkdir -p debian/opt/samson/include/samson/modules/system
mkdir -p debian/opt/samson/lib
mkdir -p debian/opt/samson/share/modules/moduletemplate
mkdir -p debian/opt/samson/bin

echo "Package: $package_name"                                   > debian/DEBIAN/control
echo "Version: $version"                                >> debian/DEBIAN/control
echo "Section: tid"                                >> debian/DEBIAN/control
echo "Priority: optional"                                >> debian/DEBIAN/control
echo "Architecture: $arch"                              >> debian/DEBIAN/control
echo "Depends: samson, libboost-dev, ncurses-dev, make, gcc, cmake, libreadline-dev, libprotobuf-dev, protobuf-compiler, libboost-filesystem-dev, libboost-thread-dev, qt4-qmake, libqt4-dev, tid-mongodb-dev" >> debian/DEBIAN/control
echo "Maintainer: Andreu Urruela <andreu@tid.es>"       >> debian/DEBIAN/control
echo "Description: SAMSON is a high-performance MapReduce platform that is designed for scaling tasks on a cluster of commodity hardware. This platform removes the need to develop a system for parallelizing and synchronizing work between servers, allowing a person to develop the analytical models needed to solve both current and future problems.  SAMSON extends the traditional MapReduce paradigm by allowing an external data source to stream data into and out of the cluster. This allows the system to handle any volume of data thus providing the ability to continuously process new inputs and output states without restriction."  >> debian/DEBIAN/control 

cp $BUILD_ROOT/BUILD_RELEASE/libs/au/libau.a                            debian/opt/samson/lib
cp $BUILD_ROOT/BUILD_RELEASE/libs/logMsg/liblm.a                        debian/opt/samson/lib
cp $BUILD_ROOT/libs/samson/module/*.h                                   debian/opt/samson/include/samson/module
cp $BUILD_ROOT/modules/system/samson/modules/system/*                   debian/opt/samson/include/samson/modules/system
cp $BUILD_ROOT/modules/moduletemplate/CMakeLists.txt 			debian/opt/samson/share/modules/moduletemplate
cp $BUILD_ROOT/modules/moduletemplate/makefile                          debian/opt/samson/share/modules/moduletemplate
cp $BUILD_ROOT/modules/moduletemplate/module                 		debian/opt/samson/share/modules/moduletemplate
cp -r $BUILD_ROOT/scripts/samsonModuleBootstrap                  	debian/opt/samson/bin

#
# Create the package
#
dpkg-deb --build debian ${package_name}_${version}-${release}_$arch.deb
dpkg-deb -c  ${package_name}_${version}-${release}_$arch.deb
mkdir -p package/deb	
mv ${package_name}_${version}-${release}_$arch.deb package/deb
