#!/bin/sh
#
# Checking command line options
#
if [ "$#" != 3 ]
then
	echo 'samsonModuleDeb: Bad parameters'
	echo 'Usage: samsonModuleDeb <Module Name> <Version (e.g. 0.5)> <Release (e.g. 3)>'
	exit 1
fi



#
# Using command line options
#
module=$1
lowercase_module=$(echo $module | tr 'A-Z' 'a-z' | sed 's/_/\-/g')
version=$2
release=$3



#
# Help variables
#
arch=$(dpkg --print-architecture)


#
# Populating debian
#
if [ -d debian ]; then
    rm -rf debian
fi

mkdir -p debian/DEBIAN
mkdir -p debian/opt/samson/{include,modules}


echo "Package: samson-${lowercase_module}"                 > debian/DEBIAN/control
echo "Version: $version"                                >> debian/DEBIAN/control
echo "Architecture: $arch"                              >> debian/DEBIAN/control
echo "Section: tid"                                >> debian/DEBIAN/control
echo "Priority: optional"                                >> debian/DEBIAN/control
echo "Maintainer: Andreu Urruela <andreu@tid.es>"       >> debian/DEBIAN/control
echo "Depends: samson (=${version})"       >> debian/DEBIAN/control
echo "Description: Module ${lowercase_module} for use with the Samson Map Reduce Platform."  >> debian/DEBIAN/control

mkdir -p debian/opt/samson/include/samson/modules/$module
cp /opt/samson/include/samson/modules/$module/*.h   debian/opt/samson/include/samson/modules/${lowercase_module}
cp /opt/samson/modules/lib$module.so               debian/opt/samson/modules



#
# Create package
#
dpkg-deb --build debian samson-${lowercase_module}_$version-${release}_$arch.deb
mkdir -p ../../package/deb
mv samson-${lowercase_module}_$version-${release}_$arch.deb ../../package/deb/samson-${lowercase_module}_$version-${release}_$arch.deb
