#!/bin/bash
##
# Checking command line options
#
if [ "$#" != 2 ]
then
    echo 'samsonRpm: Bad parameters'
    echo 'Usage: samsonRpm <Version (e.g. 0.5)> <Release (e.g. 3)>'
    exit 1
fi



#
# Using command line options
#
version=$1
release=$2



#
# Help variables
#
vr=$version.$release
samson_tarfile=samson-$version.tar.gz
samson_devel_tarfile=samson-devel-$version.tar.gz
specfile=samson-$vr.spec
rdir=samson-$version
rdir_devel=samson-devel-$version
rdir_docs=samson-docs-$version
BUILD_ROOT=$(pwd)
PACKAGE_DIR=${BUILD_ROOT}/rpm/scratch/$rdir
PACKAGE_DEV_DIR=${BUILD_ROOT}/rpm/scratch/$rdir_devel
PACKAGE_DEV_DIR=${BUILD_ROOT}/rpm/scratch/$rdir_devel



#
# Preparing BUILD_ROOT directory for RPM
#
echo "%_topdir $BUILD_ROOT/rpm" > ~/.rpmmacros
echo "%_unpackaged_files_terminate_build      0" >> ~/.rpmmacros

if [ ! -d $BUILD_ROOT/rpm ];
then
    mkdir -p $BUILD_ROOT/rpm/{SOURCES,SPECS,BUILD,SRPMS,BUILDROOT}
fi




#
# Creating link for 'compiled stuff' ...
#
arch=$(uname -p)
ln -s $BUILD_ROOT/rpm/BUILD/samson-$version $BUILD_ROOT/rpm/BUILDROOT/samson-$version-$release.$arch



#
# Creating the SPEC file
#
echo "Summary:   Samson Map Reduce Platform"                  > $BUILD_ROOT/rpm/SPECS/$specfile
echo "Name:      samson"                                     >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "Version:   " $version                                  >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "Release:   " $release                                  >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "License:   commercial"                                 >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "Group:     Applications/Engineering"                   >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "Source:    http://www.tid.es/samson-$version.tar.gz"   >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "BuildRoot: /var/tmp/%{name}-buildroot"                 >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "Requires: protobuf, ntp,tid-mongodb, kdchart"          >> $BUILD_ROOT/rpm/SPECS/$specfile 
echo "Requires(pre): shadow-utils"                           >> $BUILD_ROOT/rpm/SPECS/$specfile 
echo                                                         >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%description"                                          >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "SAMSON is a high-performance MapReduce platform that is designed for scaling tasks on a cluster of commodity hardware. This platform removes the need to develop a system for parallelizing and synchronizing work between servers, allowing a person to develop the analytical models needed to solve both current and future problems.  SAMSON extends the traditional MapReduce paradigm by allowing an external data source to stream data into and out of the cluster. This allows the system to handle any volume of data thus providing the ability to continuously process new inputs and output states without restriction."                    >> $BUILD_ROOT/rpm/SPECS/$specfile
echo                                                         >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%prep"                                                 >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%setup"                                                >> $BUILD_ROOT/rpm/SPECS/$specfile
echo                                                         >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%pre"  >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "getent group samson >/dev/null || groupadd -r samson"  >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "getent passwd samson >/dev/null || useradd -r -g samson -d /opt/samson -s /bin/bash -c 'SAMSON account' samson"  >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "exit 0"  >> $BUILD_ROOT/rpm/SPECS/$specfile
#echo "%install"                                              >> $BUILD_ROOT/rpm/SPECS/$specfile
echo                                                         >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%post"                                                >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "bash /opt/samson/bin/samsonInitSetup"                 >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "/sbin/chkconfig --add samson"                                >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "/sbin/chkconfig --level 35 samson on"                  >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "/etc/init.d/samson start"                                >> $BUILD_ROOT/rpm/SPECS/$specfile
echo                                                          >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%preun"                                                >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "/etc/init.d/samson stop"                                >> $BUILD_ROOT/rpm/SPECS/$specfile
echo                                                          >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%clean"                                                >> $BUILD_ROOT/rpm/SPECS/$specfile
echo                                                         >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%files"                                                >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%defattr(-, samson, samson, -)"                        >> $BUILD_ROOT/rpm/SPECS/$specfile
echo '%dir /opt/samson'                                      >> $BUILD_ROOT/rpm/SPECS/$specfile
echo '%dir /opt/samson/etc'                                  >> $BUILD_ROOT/rpm/SPECS/$specfile
echo '%dir /opt/samson/log'                                  >> $BUILD_ROOT/rpm/SPECS/$specfile
echo '%dir /var/samson'                                      >> $BUILD_ROOT/rpm/SPECS/$specfile
echo '/opt/samson/bin/samson*'                               >> $BUILD_ROOT/rpm/SPECS/$specfile
echo '/opt/samson/bin/delilah*'                              >> $BUILD_ROOT/rpm/SPECS/$specfile
echo '/var/samson/etc/setup.txt'                             >> $BUILD_ROOT/rpm/SPECS/$specfile
echo '%attr(755,root,root) /etc/init.d/samson'                 >> $BUILD_ROOT/rpm/SPECS/$specfile
echo '%attr(-,root,root) /etc/profile.d/samson.sh'           >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%changelog"                                            >> $BUILD_ROOT/rpm/SPECS/$specfile
echo                                                         >> $BUILD_ROOT/rpm/SPECS/$specfile
#Definition for the devel package
echo "%package devel"                           >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "Summary: Headers and libraries for Samson development."  >> $BUILD_ROOT/rpm/SPECS/$specfile 
echo "Group: Applications/Engineering"            >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "Requires: samson = $version, protobuf-devel, gcc, gcc-c++, make, ncurses-devel, boost-devel, tid-mongodb-devel"  >> $BUILD_ROOT/rpm/SPECS/$specfile
echo                                     >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%description devel"                               >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "SAMSON is a high-performance MapReduce platform that is designed for scaling tasks on a cluster of commodity hardware. This platform removes the need to develop a system for parallelizing and synchronizing work between servers, allowing a person to develop the analytical models needed to solve both current and future problems.  SAMSON extends the traditional MapReduce paradigm by allowing an external data source to stream data into and out of the cluster. This allows the system to handle any volume of data thus providing the ability to continuously process new inputs and output states without restriction."                    >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%files devel"                    				>> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%defattr(-, samson, samson, -)"                        >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "/opt/samson/lib/libau.a"                			>> $BUILD_ROOT/rpm/SPECS/$specfile
echo "/opt/samson/lib/liblm.a"                			>> $BUILD_ROOT/rpm/SPECS/$specfile
echo "/opt/samson/include/samson/module/*"        		>> $BUILD_ROOT/rpm/SPECS/$specfile
echo "/opt/samson/include/samson/modules/system/*"    		>> $BUILD_ROOT/rpm/SPECS/$specfile
echo "/opt/samson/share/modules/*"    				>> $BUILD_ROOT/rpm/SPECS/$specfile
echo "/opt/samson/bin/samsonModuleBootstrap"			>> $BUILD_ROOT/rpm/SPECS/$specfile
echo                                                         	>> $BUILD_ROOT/rpm/SPECS/$specfile
#Definition for the docs package
echo "%package docs"                           >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "Summary: Documentation for the SAMSON Platform."  >> $BUILD_ROOT/rpm/SPECS/$specfile 
echo "Group: Applications/Engineering"            >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "Requires: samson = $version"  >> $BUILD_ROOT/rpm/SPECS/$specfile
echo                                     >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%description docs"                               >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "SAMSON is a high-performance MapReduce platform that is designed for scaling tasks on a cluster of commodity hardware. This platform removes the need to develop a system for parallelizing and synchronizing work between servers, allowing a person to develop the analytical models needed to solve both current and future problems.  SAMSON extends the traditional MapReduce paradigm by allowing an external data source to stream data into and out of the cluster. This allows the system to handle any volume of data thus providing the ability to continuously process new inputs and output states without restriction."                    >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%files docs"                    >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "%defattr(-, samson, samson, -)"                        >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "/opt/samson/man/*"                >> $BUILD_ROOT/rpm/SPECS/$specfile
echo "/opt/samson/share/*"                >> $BUILD_ROOT/rpm/SPECS/$specfile

#
# Prepare the files needed for the "samson" package
#
rm -rf $PACKAGE_DIR
mkdir -p $PACKAGE_DIR/opt/samson/{bin,etc,man,log}
mkdir -p $PACKAGE_DIR/var/samson
mkdir -p $PACKAGE_DIR/var/samson/etc
mkdir -p $PACKAGE_DIR/etc/profile.d
mkdir -p $PACKAGE_DIR/etc/init.d
mkdir -p $PACKAGE_DIR/opt/samson/{include,lib}
mkdir -p $PACKAGE_DIR/opt/samson/include/samson/module
mkdir -p $PACKAGE_DIR/opt/samson/include/samson/modules/system
mkdir -p $PACKAGE_DIR/opt/samson/man/{man1,man7}
mkdir -p $PACKAGE_DIR/opt/samson/share/modules
cp $BUILD_ROOT/BUILD_RELEASE/apps/samsonCat/samsonCat                   $PACKAGE_DIR/opt/samson/bin
cp $BUILD_ROOT/BUILD_RELEASE/apps/samsonController/samsonController     $PACKAGE_DIR/opt/samson/bin
cp $BUILD_ROOT/BUILD_RELEASE/apps/samsonData/samsonData                 $PACKAGE_DIR/opt/samson/bin
cp $BUILD_ROOT/BUILD_RELEASE/apps/samsonLocal/samsonLocal               $PACKAGE_DIR/opt/samson/bin
cp $BUILD_ROOT/BUILD_RELEASE/apps/samsonModuleParser/samsonModuleParser $PACKAGE_DIR/opt/samson/bin
cp $BUILD_ROOT/BUILD_RELEASE/apps/samsonSetup/samsonSetup               $PACKAGE_DIR/opt/samson/bin
cp $BUILD_ROOT/BUILD_RELEASE/apps/samsonSpawner/samsonSpawner           $PACKAGE_DIR/opt/samson/bin
cp $BUILD_ROOT/BUILD_RELEASE/apps/samsonWorker/samsonWorker             $PACKAGE_DIR/opt/samson/bin
cp $BUILD_ROOT/BUILD_RELEASE/apps/samsonKiller/samsonKiller             $PACKAGE_DIR/opt/samson/bin
cp $BUILD_ROOT/BUILD_RELEASE/apps/samsonStarter/samsonStarter           $PACKAGE_DIR/opt/samson/bin
cp $BUILD_ROOT/BUILD_RELEASE/apps/samsonLevelMonitor/samsonLevelMonitor $PACKAGE_DIR/opt/samson/bin
cp $BUILD_ROOT/BUILD_RELEASE/apps/samsonTopicMonitor/samsonTopicMonitor $PACKAGE_DIR/opt/samson/bin
cp $BUILD_ROOT/BUILD_RELEASE/apps/delilah/delilah                       $PACKAGE_DIR/opt/samson/bin
cp $BUILD_ROOT/scripts/samsonProcessesSupervise		                    $PACKAGE_DIR/opt/samson/bin
cp $BUILD_ROOT/scripts/samsonInitSetup                                  $PACKAGE_DIR/opt/samson/bin
cp $BUILD_ROOT/BUILD_RELEASE/apps/samsonPush/samsonPush		            $PACKAGE_DIR/opt/samson/bin
cp $BUILD_ROOT/BUILD_RELEASE/apps/samsonPop/samsonPop		            $PACKAGE_DIR/opt/samson/bin
cp $BUILD_ROOT/BUILD_RELEASE/apps/samsonTopicMonitor/samsonTopicMonitor		$PACKAGE_DIR/opt/samson/bin
cp $BUILD_ROOT/BUILD_RELEASE/apps/delilahQT/delilahQT		            $PACKAGE_DIR/opt/samson/bin
cp $BUILD_ROOT/etc/setup.txt                                            $PACKAGE_DIR/var/samson/etc
cp $BUILD_ROOT/etc/init.d/samson.redhat                                 $PACKAGE_DIR/etc/init.d/samson
cp $BUILD_ROOT/etc/profile.d/samson.sh                                  $PACKAGE_DIR/etc/profile.d/samson.sh
cp $BUILD_ROOT/BUILD_RELEASE/libs/au/libau.a                            $PACKAGE_DIR/opt/samson/lib
cp $BUILD_ROOT/BUILD_RELEASE/libs/logMsg/liblm.a                        $PACKAGE_DIR/opt/samson/lib
cp $BUILD_ROOT/libs/samson/module/*.h                                   $PACKAGE_DIR/opt/samson/include/samson/module
cp $BUILD_ROOT/modules/system/samson/modules/system/*                   $PACKAGE_DIR/opt/samson/include/samson/modules/system
cp -r $BUILD_ROOT/BUILD_RELEASE/man					$PACKAGE_DIR/opt/samson
cp -r $BUILD_ROOT/README						$PACKAGE_DIR/opt/samson/share/README.txt
cp -r $BUILD_ROOT/modules/moduletemplate				$PACKAGE_DIR/opt/samson/share/modules
cp $BUILD_ROOT/scripts/samsonModuleBootstrap                  		$PACKAGE_DIR/opt/samson/bin

#
# Create the tar file for samson
#
cd $PACKAGE_DIR/..
tar cvfz $samson_tarfile $rdir 
mv $samson_tarfile $BUILD_ROOT/rpm/SOURCES

#
# And finally, create the RPM
#
cd $BUILD_ROOT/rpm/SPECS
rpmbuild -bb $specfile
if [ ! -d $BUILD_ROOT/package/rpm/ ];
then
    mkdir -p $BUILD_ROOT/package/rpm
fi
mv $BUILD_ROOT/rpm/RPMS/$arch/samson-$version-$release.$arch.rpm $BUILD_ROOT/package/rpm/
mv $BUILD_ROOT/rpm/RPMS/$arch/samson-devel-$version-$release.$arch.rpm $BUILD_ROOT/package/rpm/
mv $BUILD_ROOT/rpm/RPMS/$arch/samson-docs-$version-$release.$arch.rpm $BUILD_ROOT/package/rpm/
