#!/bin/bash
#
# A script to distribute a module across the cluster
# for the SAMSON MapReduce platform

usage()
{
  echo "Missing an argument"
  echo "Usage: $0 [-y] [-r] -m <modulename>"
  echo " -y	Don't ask if you want to perform the operation"
  echo " -r	Reload the module within the cluster"
  exit 1
}

if [ $# -lt 1 ]; then
  usage
fi

if [ -z "$SAMSON_CLUSTER" ]; then
  echo "Define SAMSON_CLUSTER with the list of machine names to distribute to:"
  echo " e.g. export SAMSON_CLUSTER=\"node1 node2 node3\""
  exit 2
fi

hostname=$(uname -n)

while getopts "m:rq" opt; do
  case $opt in
    r)
      RELOAD=y
      ;;
    q)
      QUIET=y
      ;;
    m)
      module_name=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      usage
      ;;
  esac
done

# Check to see that the module exists before distributing it
if [ ! -z "${SAMSON_HOME}" ]; then
  if [ -e ${SAMSON_HOME}/modules/lib$module_name.so ]; then 
    module_file=${SAMSON_HOME}/modules/lib$module_name.so
  fi
elif [ -e /opt/samson/modules/lib$module_name.so ]; then 
   module_file=/opt/samson/modules/lib$module_name.so
else
  echo "Unable to locate lib${module_name}"
fi

if [ "$QUIET" != "y" ]; then
  while true; do
    read -p "Are you sure you want to distribute '$module_name'? " ans
    case $ans in
      [Yy]* ) break;;
      [Nn]* ) exit 4;;
    esac
    echo "Please, answer 'Yes' or 'No'"
  done
fi

for node in `echo $SAMSON_CLUSTER`
do
  if [ "${node}" != "${hostname}" ]; then 
    echo "Copying ${module_file} to ${node}"
    scp -q $module_file $node:${module_file}
  fi
done

if [ "${RELOAD}" = "y" ]; then
  echo "Reloading SAMSON modules"
  delilah -command reload_modules
fi
