#!/bin/bash
##
# Checking command line options
#
if [ "$#" != 2 ]
then
	echo 'samsonDeb: Bad parameters'
	echo 'Usage: samsonDeb <Version (e.g. 0.5)> <Release (e.g. 3)>'
	exit 1
fi



#
# Using command line options
#
version=$1
release=$2



#
# Help variables
#
arch=$(dpkg --print-architecture)



#
# Populating debian
#
if [ -d debian ]; then
    rm -rf debian
fi

mkdir -p debian/DEBIAN
# Create the base structure needed
mkdir -p debian/opt/samson/bin
mkdir -p debian/opt/samson/etc
mkdir -p debian/var/samson/etc
mkdir -p debian/opt/samson/data
mkdir -p debian/opt/samson/blocks
mkdir -p debian/opt/samson/log
mkdir -p debian/opt/samson/config
mkdir -p debian/opt/samson/share
mkdir -p debian/etc/init.d
mkdir -p debian/etc/profile.d
mkdir -p debian/etc/defaults

echo "Package: samson"                                   > debian/DEBIAN/control
echo "Version: $version"                                >> debian/DEBIAN/control
echo "Section: tid"                                     >> debian/DEBIAN/control
echo "Priority: optional"                               >> debian/DEBIAN/control
echo "Architecture: $arch"                              >> debian/DEBIAN/control
echo "Depends: libprotobuf6, ntp, tid-mongodb"          >> debian/DEBIAN/control
echo "Maintainer: Andreu Urruela <andreu@tid.es>"       >> debian/DEBIAN/control
echo "Description: SAMSON is a high-performance MapReduce platform that is designed for scaling tasks on a cluster of commodity hardware. This platform removes the need to develop a system for parallelizing and synchronizing work between servers, allowing a person to develop the analytical models needed to solve both current and future problems.  SAMSON extends the traditional MapReduce paradigm by allowing an external data source to stream data into and out of the cluster. This allows the system to handle any volume of data thus providing the ability to continuously process new inputs and output states without restriction."  >> debian/DEBIAN/control 

cat > debian/DEBIAN/preinst <<PREINST
#!/bin/sh
getent group samson >/dev/null || groupadd -r samson
getent passwd samson >/dev/null || useradd -r -g samson -d /opt/samson -s /bin/bash -c 'SAMSON Platform account' samson
#Force the bash shell since useradd does not appear to set it correctly
chsh -s /bin/bash samson
PREINST
chmod 0755 debian/DEBIAN/preinst

cat > debian/DEBIAN/postinst <<POSTINST
#!/bin/sh
chown -R samson:samson /opt/samson
chown -R samson:samson /var/samson
update-rc.d samson defaults
/etc/init.d/samson start
POSTINST
chmod 0755 debian/DEBIAN/postinst

cat > debian/DEBIAN/prerm <<PRERM
#!/bin/sh
/etc/init.d/samson stop
PRERM
chmod 0755 debian/DEBIAN/prerm
 
cp BUILD_RELEASE/apps/samsonCat/samsonCat              debian/opt/samson/bin
cp BUILD_RELEASE/apps/samsonController/samsonController       debian/opt/samson/bin
cp BUILD_RELEASE/apps/samsonData/samsonData             debian/opt/samson/bin
cp BUILD_RELEASE/apps/samsonLocal/samsonLocal            debian/opt/samson/bin
cp BUILD_RELEASE/apps/samsonModuleParser/samsonModuleParser     debian/opt/samson/bin
cp BUILD_RELEASE/apps/samsonSetup/samsonSetup            debian/opt/samson/bin
cp BUILD_RELEASE/apps/samsonSpawner/samsonSpawner          debian/opt/samson/bin
cp BUILD_RELEASE/apps/samsonWorker/samsonWorker           debian/opt/samson/bin
cp BUILD_RELEASE/apps/samsonKiller/samsonKiller           debian/opt/samson/bin
cp BUILD_RELEASE/apps/samsonStarter/samsonStarter           debian/opt/samson/bin
cp BUILD_RELEASE/apps/delilah/delilah               debian/opt/samson/bin
cp etc/setup.txt                                    debian/var/samson/etc
cp etc/setup.txt                                    debian/opt/samson/etc
cp etc/profile.d/samson.sh                          debian/etc/profile.d/samson.sh
cp etc/init.d/samson.ubuntu                         debian/etc/init.d/samson
cp README debian/opt/samson/share



#
# Create package
#
dpkg-deb --build debian samson_$version-${release}_$arch.deb
mkdir -p package/deb	
mv samson_$version-${release}_$arch.deb package/deb/samson_$version-${release}_$arch.deb
