#!/bin/bash

# This is necessary in some remove console wnvironments
export TERM=vt100

# #############################################################################
#
# samsonProcesses -
#
function samsonProcesses
{
	echo '------------------------ Samson Platform process list ------------------------'
	ps aux | egrep "${SAMSON_HOME}/bin/samsonWorker|${SAMSON_HOME}/bin/samsonController|samsonSpawner" | grep -v '<defunct>' | grep -v egrep | sort
	echo '------------------------------------------------------------------------------'
}



# #############################################################################
#
# looping ...
#
while /bin/true
do
	clear
	samsonProcesses
	sleep 1
done
