#!/bin/bash

# If we have a directory we'll run a suite of tests
if [ -d $1 ];
then
    TEST_DIR=$1
fi

# Execute an individual test
if [ -f $1 ];
then
    TEST_DIR=$(dirname $1)
    TEST_FILE=$(basename $1)
fi

if [ -z "${TEST_DIR}" ]
then
    echo "ERROR: $1 does not exist"
    exit 1
fi

function execute_test
{
    TEST_BASENAME=$(echo $TEST_FILE | sed 's/\.test//')
    TEST_NAME=$(sed -n '/--NAME--/,/^--/p' $TEST_FILE  | grep -v "^--")

    #Extract the init script
    TEST_INIT_SCRIPT=${TEST_BASENAME}.init
    sed -n '/--INIT--/,/^--/p' $TEST_FILE  | grep -v "^--" > $TEST_INIT_SCRIPT

    #Extract the test script
    TEST_COMMAND=$(sed -n '/--SCRIPT--/,/^--/p' $TEST_FILE  | grep -v "^--")

    TEST_EXPECT=${TEST_BASENAME}.expect
    #Generate the canon file
    sed -n '/--EXPECT--/,/^--/p' $TEST_FILE  | grep -v "^--" > $TEST_EXPECT
    TEST_DIFF=${TEST_BASENAME}.diff
    TEST_OUTPUT=${TEST_BASENAME}.out

	# ------------------------------------------------ 
	# Initialize the test
	# ------------------------------------------------ 
	if [ -f delilah_commands ]; then
	   echo "Initializing the test" 
	   delilah -f $TEST_INIT_SCRIPT 2>$TEST_INIT_SCRIPT.stderr >$TEST_INIT_SCRIPT.stdout
	fi		  
    
    # ------------------------------------------------
    # Execute script
    # ------------------------------------------------
    delilah -command  $TEST_COMMAND > $TEST_OUTPUT 2>/dev/null

    # Check to see if the output is what we expect
    diff -u $TEST_EXPECT $TEST_OUTPUT > $TEST_DIFF
    if [ $? -ne 0 ]; then
        echo "ERROR: $TEST_NAME"
        echo "Diffs"
        cat $TEST_DIFF
    else
        # Clean up files for succesfull test runs
        rm $TEST_EXPECT $TEST_OUTPUT $TEST_SCRIPT $TEST_INIT_SCRIPT ${TEST_BASENAME}.diff $TEST_INIT_SCRIPT.stderr $TEST_INIT_SCRIPT.stdout
        echo "SUCCESS: $TEST_NAME"
    fi

}

pushd $TEST_DIR
if [ -z ${TEST_FILE} ];
then
    for test in *.test
    do
        TEST_FILE=$test
        execute_test
    done
else
    execute_test
fi
popd
exit 0
