
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_plot_LevelUpdate
#define _H_SAMSON_plot_LevelUpdate



#include <samson/modules/plot/LevelUpdate_base.h>

#include "common.h" // Commmon definitions

namespace samson{
namespace plot{


	class LevelUpdate : public LevelUpdate_base
	{

	public:

	   void increment( double _value )
	   {
		  command.value = plot_level_increment;
		  level.value = _value;
	   }

	   void decrement( double _value )
	   {
		  command.value = plot_level_decrement;
		  level.value = _value;
	   }

	   void set( double _value )
	   {
		  command.value = plot_level_set;
		  level.value = _value;
	   }

	   std::string str()
	   {
		  std::ostringstream output;

		  if( command.value == plot_level_increment )
			 output << "Increment " << level.value;
		  else if( command.value == plot_level_decrement )
			 output << "Decrement " << level.value;
		  else if( command.value == plot_level_set )
			 output << "Set " << level.value;
		  else
			 output << "Unknown";


		  return output.str();
		  
	   }

	};


} // end of namespace samson
} // end of namespace plot

#endif
