/*
 * Telefónica Digital - Product Development and Innovation
 *
 * THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 *
 * Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
 * All rights reserved.
 */

/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_testcomparefunctions_Company
#define _H_SAMSON_testcomparefunctions_Company


#include <samson/modules/testcomparefunctions/Company_base.h>


namespace samson{
namespace testcomparefunctions{


	class Company : public Company_base
	{
	};


} // end of namespace samson
} // end of namespace testcomparefunctions

#endif
