
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_testcomparefunctions_Company
#define _H_SAMSON_testcomparefunctions_Company


#include <samson/modules/testcomparefunctions/Company_base.h>


namespace samson{
namespace testcomparefunctions{


	class Company : public Company_base
	{
	};


} // end of namespace samson
} // end of namespace testcomparefunctions

#endif
