
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_sna_parse_links_gasset_to_nodes
#define _H_SAMSON_sna_parse_links_gasset_to_nodes


#include <samson/module/samson.h>


namespace samson{
namespace sna{


	class parse_links_gasset_to_nodes : public samson::Script
	{

	public:




	};


} // end of namespace samson
} // end of namespace sna

#endif
