
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_mob2_NodeMx_Counter
#define _H_SAMSON_mob2_NodeMx_Counter


#include <samson/modules/mob2/NodeMx_Counter_base.h>


namespace samson{
namespace mob2{


	class NodeMx_Counter : public NodeMx_Counter_base
	{
	};


} // end of namespace samson
} // end of namespace mob2

#endif
