
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_shop_test_generator_fixed
#define _H_SAMSON_shop_test_generator_fixed


#include <samson/module/samson.h>


namespace samson{
namespace shop{


	class test_generator_fixed : public samson::Generator
	{

	public:


		void run( samson::KVWriter *writer )
		{
            size_t num_samples = environment->getInt( "shop.samples", 10000);

            samson::system::UInt id;
            samson::shop::Transaction operation;

            for (size_t i = 0; (i < num_samples); i++)
            {
                    id = i;
                    operation.user = i%100;
                    operation.product = i%1000;
                    operation.operationType = i%2;

                    writer->emit(0, &id, &operation);
            }
		}


	};


} // end of namespace samson
} // end of namespace shop

#endif
