
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_shop_test_generator
#define _H_SAMSON_shop_test_generator


#include <samson/module/samson.h>
#include <samson/modules/shop/Transaction.h>
#include <samson/modules/system/UInt.h>


namespace samson{
namespace shop{


	class test_generator : public samson::Generator
	{

	public:


#ifdef INFO_COMMENT //Just to include a comment without conflicting anything
// If interface changes and you do not recreate this file, consider updating this information (and of course, the module file)

output: system.UInt shop.Transaction

helpLine: Simple generator that generates shop.Transaction operations
#endif // de INFO_COMMENT

		void init( samson::KVWriter *writer )
		{
		}

		void setup( int worker , int num_workers, int process , int num_processes )
		{
		}

		void run( samson::KVWriter *writer )
		{
            size_t num_samples = environment->getInt( "shop.samples", 100000);

            samson::system::UInt id;
            samson::shop::Transaction operation;

            for (size_t i = 0; (i < num_samples); i++)
            {
                    id = i;
                    operation.user = rand()%10000;
                    operation.product = rand()%100;
                    operation.operationType = rand()%2;

                    writer->emit(0, &id, &operation);
            }
		}

		void finish( samson::KVWriter *writer )
		{
		}



	};


} // end of namespace shop
} // end of namespace samson

#endif
