
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_mob2_CellMx
#define _H_SAMSON_mob2_CellMx


#include <samson/modules/mob2/CellMx_base.h>


namespace samson{
namespace mob2{


	class CellMx : public CellMx_base
	{
	};


} // end of namespace samson
} // end of namespace mob2

#endif
