
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_mob2_ItinPercMove
#define _H_SAMSON_mob2_ItinPercMove


#include <samson/modules/mob2/ItinPercMove_base.h>


namespace samson{
namespace mob2{


	class ItinPercMove : public ItinPercMove_base
	{
	};


} // end of namespace samson
} // end of namespace mob2

#endif
