/*
 * Telefónica Digital - Product Development and Innovation
 *
 * THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 *
 * Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
 * All rights reserved.
 */

/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_mob2_Mob_VI_MobVars
#define _H_SAMSON_mob2_Mob_VI_MobVars


#include <samson/modules/mob2/Mob_VI_MobVars_base.h>


namespace samson{
namespace mob2{


	class Mob_VI_MobVars : public Mob_VI_MobVars_base
	{
	};


} // end of namespace samson
} // end of namespace mob2

#endif
