/*
 * Telefónica Digital - Product Development and Innovation
 *
 * THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 *
 * Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
 * All rights reserved.
 */

/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_web_parse_web_hits
#define _H_SAMSON_web_parse_web_hits


#include <samson/module/samson.h>
#include <samson/modules/system/String.h>
#include <samson/modules/system/UInt.h>
#include <samson/modules/system/SimpleParser.h>

#include <logMsg/logMsg.h>

namespace samson{
namespace web{


   class parse_web_hits : public samson::system::SimpleParser
	{

	   samson::system::String key;
	   samson::system::UInt value;

	public:


//  INFO_MODULE
// If interface changes and you do not recreate this file, you will have to update this information (and of course, the module file)
// Please, do not remove this comments, as it will be used to check consistency on module declaration
//
//  output: system.String system.UInt
// 
//  END_INFO_MODULE

		void init( samson::KVWriter *writer )
		{
			  value.value = 1;
		}

		void parseLine( char * line , samson::KVWriter *writer )
		{
		   // Get the line in a c++ string                                                                                          
		   std::vector<char*> words;

		   // Split input line in words
		   split_in_words(line, words);

		   
		   // Emit the thirs element as it is
		   if( words.size() >= 4 )
		   {
			  key.value = "ip ";
			  key.value.append(  words[3] );
			  writer->emit( 0 , &key , &value);
		   }
		   else
		   {
			LM_E(("Error, line too short:'%s'", line));
		   }
		   

		   // Emit full URL as 4th and 7th field
		   if( words.size() >= 7 )
		   {
			  key.value = "url ";
			  key.value.append( words[3] );
			  key.value.append( words[6] );
			  writer->emit( 0 , &key , &value);
		   }
		   
           // Emit the 9th field as protocol
		   if ( words.size() >= 8 )
		   {
			  key.value = "protocol ";
			  key.value.append(words[7]);
			  writer->emit(0,&key,&value);
		   }

           if ( words.size() >= 6 )
           {
              key.value = "operation ";
              key.value.append(words[5]);
              writer->emit(0,&key,&value);
           }

		}

		void finish( samson::KVWriter *writer )
		{
		}



	};


} // end of namespace web
} // end of namespace samson

#endif
