
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_mobility_Record
#define _H_SAMSON_mobility_Record


#include <samson/modules/mobility/Record_base.h>


namespace samson{
namespace mobility{


	class Record : public Record_base
	{
	};


} // end of namespace samson
} // end of namespace mobility

#endif
