
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_osn_Bytemobile_req_1
#define _H_SAMSON_osn_Bytemobile_req_1


#include <samson/module/samson.h>


namespace samson{
namespace osn{


	class Bytemobile_req_1 : public samson::Script
	{

	public:




	};


} // end of namespace samson
} // end of namespace osn

#endif
