
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_osn_bytemobile_req
#define _H_SAMSON_osn_bytemobile_req


#include <samson/module/samson.h>


namespace samson{
namespace osn{


	class bytemobile_req : public samson::Script
	{

	public:




	};


} // end of namespace samson
} // end of namespace osn

#endif
