
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_graph_accumulate_cdrs_into_links
#define _H_SAMSON_graph_accumulate_cdrs_into_links


#include <samson/module/samson.h>


namespace samson{
namespace graph{


	class accumulate_cdrs_into_links : public samson::Script
	{

	public:




	};


} // end of namespace samson
} // end of namespace graph

#endif
