
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_fiware_pos_Position
#define _H_SAMSON_fiware_pos_Position


#include <samson/modules/fiware_pos/Position_base.h>


namespace samson{
namespace fiware_pos{


	class Position : public Position_base
	{
	};


} // end of namespace samson
} // end of namespace fiware_pos

#endif
