
/**
 File autogenerated with samsonModuleParser, please do not edit
*/

#ifndef _H_SAMSON_url_ServerStrPathVector_BASE
#define _H_SAMSON_url_ServerStrPathVector_BASE


#include <samson/modules/system/UInt.h>
#include <samson/modules/url/ServerStrPath.h>


namespace samson{
namespace url{


	class ServerStrPathVector_base : public samson::DataInstance{

	public:
	::samson::url::ServerStrPath *serverStrPath;
	int serverStrPath_length;
	int serverStrPath_max_length;
	::samson::system::UInt countRef;

	ServerStrPathVector_base() : samson::DataInstance(){
		serverStrPath_length=0;
		serverStrPath_max_length=0;
		serverStrPath = NULL;
	}

	~ServerStrPathVector_base() {
		if( serverStrPath )
			delete[] serverStrPath ;
	}

	int parse(char *data){
		int offset=0;
		{ //Parsing vector serverStrPath
			size_t _length;
			offset += samson::staticVarIntParse( data+offset , &_length );
		 	serverStrPathSetLength( _length );
			for (int i = 0 ; i < (int)serverStrPath_length ; i++)
			{ //Parsing serverStrPath
				offset += serverStrPath[i].parse(data+offset);
			}

		}

		{ //Parsing countRef
			offset += countRef.parse(data+offset);
		}

		return offset;
	}

	int serialize(char *data){
		int offset=0;
		{ //Serialization vector serverStrPath
			offset += samson::staticVarIntSerialize( data+offset , serverStrPath_length );
			for (int i = 0 ; i < (int)serverStrPath_length ; i++)
			{ //Serializing serverStrPath
				offset += serverStrPath[i].serialize(data+offset);
			}

		}

		{ //Serializing countRef
			offset += countRef.serialize(data+offset);
		}

		return offset;
	}

	static inline int size(char *data){
		int offset=0;
		{ //Getting size of vector serverStrPath
			size_t _length;
			offset += samson::staticVarIntParse( data+offset , &_length );
			::samson::url::ServerStrPath _tmp;
			for (int i = 0 ; i < (int)_length ; i++)
			{ //Sizing serverStrPath
				offset += ::samson::url::ServerStrPath::size(data+offset);
			}

		}

		{ //Sizing countRef
			offset += ::samson::system::UInt::size(data+offset);
		}

		return offset;
	}

	int hash(int max_num_partitions){
		if( serverStrPath_length > 0 )
			{ //Partitioning serverStrPath
				return serverStrPath[0].hash(max_num_partitions);
			}

		else return 0;

	}

	inline static int compare(char * data1 , char *data2 , size_t *offset1 , size_t *offset2 ){
		{ // Comparing vector serverStrPath
			size_t _length1,_length2;
			*offset1 += samson::staticVarIntParse( data1+(*offset1) , &_length1 );
			*offset2 += samson::staticVarIntParse( data2+(*offset2) , &_length2 );
			if( _length1 < _length2 ) return -1;
			if( _length1 > _length2 ) return 1;
			for (int i = 0 ; i < (int)_length1 ; i++)
			{ // comparing serverStrPath[i]
				int tmp = ::samson::url::ServerStrPath::compare(data1,data2,offset1 , offset2);
				if( tmp != 0) return tmp;
			}   //  serverStrPath[i] compared 
		}   // vector serverStrPath compared 
		{ // comparing countRef
			int tmp = ::samson::system::UInt::compare(data1,data2,offset1 , offset2);
			if( tmp != 0) return tmp;
		}   //  countRef compared 
		return 0; //If everything is equal
	}

	inline static int compare( char* data1 , char* data2 )
	{
		size_t offset_1=0;
		size_t offset_2=0;
		return compare( data1 , data2 , &offset_1 , &offset_2 );
	}




	void serverStrPathSetLength(int _length){
		if( _length > serverStrPath_max_length){ 
			::samson::url::ServerStrPath *_previous = serverStrPath;
			int previous_length = serverStrPath_length;
			if(serverStrPath_max_length == 0) serverStrPath_max_length = _length;
			while(serverStrPath_max_length < _length) serverStrPath_max_length *= 2;
			serverStrPath = new ::samson::url::ServerStrPath[serverStrPath_max_length ];
			if( _previous ){
				for (int i = 0 ; i < previous_length ; i++)
					serverStrPath[i].copyFrom( &_previous[i] );
				delete[] _previous;
			}
		}
		serverStrPath_length=_length;
	}

	::samson::url::ServerStrPath* serverStrPathAdd(){
		serverStrPathSetLength( serverStrPath_length + 1 );
		return &serverStrPath[serverStrPath_length-1];
	}

	void copyFrom( ServerStrPathVector_base *other ){
		{ // CopyFrom field serverStrPath
			serverStrPathSetLength( other->serverStrPath_length);
			for (int i = 0 ; i < serverStrPath_length ; i++)
			{ //Copying serverStrPath
				serverStrPath[i].copyFrom(&other->serverStrPath[i]);
			}
		}

		{ //Copying countRef
			countRef.copyFrom(&other->countRef);
		}

	};

	std::string str(){
		std::ostringstream o;
		{// toString of vector serverStrPath
			for(int i = 0 ; i < serverStrPath_length ; i++)
			{ //Texting serverStrPath
				o << serverStrPath[i].str();
			}
				 o << " ";
		}

		o<<" ";
				{ //Texting countRef
			o << countRef.str();
		}

		o<<" ";
		return o.str();
	}

	}; //class ServerStrPathVector_base

} // end of namespace samson
} // end of namespace url

#endif
