
/**
 File autogenerated with samsonModuleParser, please do not edit
*/

#ifndef _H_SAMSON_url_ServerStrPath_BASE
#define _H_SAMSON_url_ServerStrPath_BASE


#include <samson/modules/system/String.h>


namespace ss{
namespace url{


	class ServerStrPath_base : public ss::DataInstance{

	public:
	::ss::system::String server;
	::ss::system::String path;

	ServerStrPath_base() : ss::DataInstance(){
	}

	~ServerStrPath_base() {
	}

	int parse(char *data){
		int offset=0;
		offset += server.parse(data+offset);
		offset += path.parse(data+offset);
		return offset;
	}

	int serialize(char *data){
		int offset=0;
		offset += server.serialize(data+offset);
		offset += path.serialize(data+offset);
		return offset;
	}

	static inline int size(char *data){
		int offset=0;
		offset += ::ss::system::String::size(data+offset);
		offset += ::ss::system::String::size(data+offset);
		return offset;
	}

	int hash(int max_num_partitions){
		return server.hash(max_num_partitions);
	}

	inline static int compare(char * data1 , char *data2 , size_t *offset1 , size_t *offset2 ){
		{ // comparing server
			int tmp = ::ss::system::String::compare(data1,data2,offset1 , offset2);
			if( tmp != 0) return tmp;
		}
		{ // comparing path
			int tmp = ::ss::system::String::compare(data1,data2,offset1 , offset2);
			if( tmp != 0) return tmp;
		}
		return 0; //If everything is equal
	}

	inline static int compare( char* data1 , char* data2 )
	{
		size_t offset_1=0;
		size_t offset_2=0;
		return compare( data1 , data2 , &offset_1 , &offset_2 );
	}

	void copyFrom( ServerStrPath_base *other ){
		server.copyFrom(&other->server);
		path.copyFrom(&other->path);
	};

	std::string str(){
		std::ostringstream o;
		o << server.str();

		o<<" ";
		o << path.str();

		o<<" ";
		return o.str();
	}

	}; //class ServerStrPath_base

} // end of namespace ss
} // end of namespace url

#endif
