
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this data
*/

#ifndef _H_SAMSON_url_ServerStrPathVector
#define _H_SAMSON_url_ServerStrPathVector


#include <samson/modules/url/ServerStrPathVector_base.h>


namespace samson{
namespace url{


	class ServerStrPathVector : public ServerStrPathVector_base
	{
	};


} // end of namespace samson
} // end of namespace url

#endif
