
/**
 File autogenerated with samsonModuleParser, please do not edit
*/

#ifndef _H_SAMSON_url_URL_BASE
#define _H_SAMSON_url_URL_BASE


#include <samson/modules/system/String.h>
#include <samson/modules/system/UInt.h>
#include <samson/modules/system/UInt8.h>


namespace samson{
namespace url{


	class URL_base : public samson::DataInstance{

	public:
	::samson::system::String server;
	::samson::system::UInt8 type;
	::samson::system::String path;
	::samson::system::UInt user;

	URL_base() : samson::DataInstance(){
	}

	~URL_base() {
	}

	int parse(char *data){
		int offset=0;
		{ //Parsing server
			offset += server.parse(data+offset);
		}

		{ //Parsing type
			offset += type.parse(data+offset);
		}

		{ //Parsing path
			offset += path.parse(data+offset);
		}

		{ //Parsing user
			offset += user.parse(data+offset);
		}

		return offset;
	}

	int serialize(char *data){
		int offset=0;
		{ //Serializing server
			offset += server.serialize(data+offset);
		}

		{ //Serializing type
			offset += type.serialize(data+offset);
		}

		{ //Serializing path
			offset += path.serialize(data+offset);
		}

		{ //Serializing user
			offset += user.serialize(data+offset);
		}

		return offset;
	}

	static inline int size(char *data){
		int offset=0;
		{ //Sizing server
			offset += ::samson::system::String::size(data+offset);
		}

		{ //Sizing type
			offset += ::samson::system::UInt8::size(data+offset);
		}

		{ //Sizing path
			offset += ::samson::system::String::size(data+offset);
		}

		{ //Sizing user
			offset += ::samson::system::UInt::size(data+offset);
		}

		return offset;
	}

	int hash(int max_num_partitions){
		{ //Partitioning server
			return server.hash(max_num_partitions);
		}

	}

	inline static int compare(char * data1 , char *data2 , size_t *offset1 , size_t *offset2 ){
		{ // comparing server
			int tmp = ::samson::system::String::compare(data1,data2,offset1 , offset2);
			if( tmp != 0) return tmp;
		}   //  server compared 
		{ // comparing type
			int tmp = ::samson::system::UInt8::compare(data1,data2,offset1 , offset2);
			if( tmp != 0) return tmp;
		}   //  type compared 
		{ // comparing path
			int tmp = ::samson::system::String::compare(data1,data2,offset1 , offset2);
			if( tmp != 0) return tmp;
		}   //  path compared 
		{ // comparing user
			int tmp = ::samson::system::UInt::compare(data1,data2,offset1 , offset2);
			if( tmp != 0) return tmp;
		}   //  user compared 
		return 0; //If everything is equal
	}

	inline static int compare( char* data1 , char* data2 )
	{
		size_t offset_1=0;
		size_t offset_2=0;
		return compare( data1 , data2 , &offset_1 , &offset_2 );
	}






	void copyFrom( URL_base *other ){
		{ //Copying server
			server.copyFrom(&other->server);
		}

		{ //Copying type
			type.copyFrom(&other->type);
		}

		{ //Copying path
			path.copyFrom(&other->path);
		}

		{ //Copying user
			user.copyFrom(&other->user);
		}

	};

	std::string str(){
		std::ostringstream o;
				{ //Texting server
			o << server.str();
		}

		o<<" ";
				{ //Texting type
			o << type.str();
		}

		o<<" ";
				{ //Texting path
			o << path.str();
		}

		o<<" ";
				{ //Texting user
			o << user.str();
		}

		o<<" ";
		return o.str();
	}

	}; //class URL_base

} // end of namespace samson
} // end of namespace url

#endif
