
/**
 File autogenerated with samsonModuleParser, please do not edit
*/

#ifndef _H_SAMSON_url_UserCountVector_BASE
#define _H_SAMSON_url_UserCountVector_BASE


#include <samson/modules/system/UInt.h>
#include <samson/modules/url/UserCount.h>


namespace samson{
namespace url{


	class UserCountVector_base : public samson::DataInstance{

	public:
	::samson::url::UserCount *usersCount;
	int usersCount_length;
	int usersCount_max_length;
	::samson::system::UInt countRef;

	UserCountVector_base() : samson::DataInstance(){
		usersCount_length=0;
		usersCount_max_length=0;
		usersCount = NULL;
	}

	~UserCountVector_base() {
		if( usersCount )
			delete[] usersCount ;
	}

	int parse(char *data){
		int offset=0;
		{ //Parsing vector usersCount
			size_t _length;
			offset += samson::staticVarIntParse( data+offset , &_length );
		 	usersCountSetLength( _length );
			for (int i = 0 ; i < (int)usersCount_length ; i++){
				offset += usersCount[i].parse(data+offset);
			}
		}
		offset += countRef.parse(data+offset);
		return offset;
	}

	int serialize(char *data){
		int offset=0;
		{ //Serialization vector usersCount
			offset += samson::staticVarIntSerialize( data+offset , usersCount_length );
			for (int i = 0 ; i < (int)usersCount_length ; i++){
				offset += usersCount[i].serialize(data+offset);
			}
		}
		offset += countRef.serialize(data+offset);
		return offset;
	}

	static inline int size(char *data){
		int offset=0;
		{ //Getting size of vector usersCount
			size_t _length;
			offset += samson::staticVarIntParse( data+offset , &_length );
			::samson::url::UserCount _tmp;
			for (int i = 0 ; i < (int)_length ; i++){
				offset += ::samson::url::UserCount::size(data+offset);
			}
		}
		offset += ::samson::system::UInt::size(data+offset);
		return offset;
	}

	int hash(int max_num_partitions){
		if( usersCount_length > 0 ){
		return usersCount[0].hash(max_num_partitions);
		} else return 0;
	}

	inline static int compare(char * data1 , char *data2 , size_t *offset1 , size_t *offset2 ){
		{ // Comparing vector usersCount
			size_t _length1,_length2;
			*offset1 += samson::staticVarIntParse( data1+(*offset1) , &_length1 );
			*offset2 += samson::staticVarIntParse( data2+(*offset2) , &_length2 );
			if( _length1 < _length2 ) return -1;
			if( _length1 > _length2 ) return 1;
			for (int i = 0 ; i < (int)_length1 ; i++){
				{ // comparing usersCount[i]
					int tmp = ::samson::url::UserCount::compare(data1,data2,offset1 , offset2);
					if( tmp != 0) return tmp;
				}
			}
		}
		{ // comparing countRef
			int tmp = ::samson::system::UInt::compare(data1,data2,offset1 , offset2);
			if( tmp != 0) return tmp;
		}
		return 0; //If everything is equal
	}

	inline static int compare( char* data1 , char* data2 )
	{
		size_t offset_1=0;
		size_t offset_2=0;
		return compare( data1 , data2 , &offset_1 , &offset_2 );
	}

	void usersCountSetLength(int _length){
		if( _length > usersCount_max_length){ 
			::samson::url::UserCount *_previous = usersCount;
			int previous_length = usersCount_length;
			if(usersCount_max_length == 0) usersCount_max_length = _length;
			while(usersCount_max_length < _length) usersCount_max_length *= 2;
			usersCount = new ::samson::url::UserCount[usersCount_max_length ];
			if( _previous ){
				for (int i = 0 ; i < previous_length ; i++)
					usersCount[i].copyFrom( &_previous[i] );
				delete[] _previous;
			}
		}
		usersCount_length=_length;
	}

	::samson::url::UserCount* usersCountAdd(){
		usersCountSetLength( usersCount_length + 1 );
		return &usersCount[usersCount_length-1];
	}

	void copyFrom( UserCountVector_base *other ){
			{ // CopyFrom field usersCount
				usersCountSetLength( other->usersCount_length);
				for (int i = 0 ; i < usersCount_length ; i++){
					usersCount[i].copyFrom(&other->usersCount[i]);
				}
			}
		countRef.copyFrom(&other->countRef);
	};

	std::string str(){
		std::ostringstream o;
		{// toString of vector usersCount
			for(int i = 0 ; i < usersCount_length ; i++){
				o << usersCount[i].str();
				 o << " ";
			}
		}
		o<<" ";
		o << countRef.str();

		o<<" ";
		return o.str();
	}

	}; //class UserCountVector_base

} // end of namespace samson
} // end of namespace url

#endif
