
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_snalight_cliques_info
#define _H_SAMSON_snalight_cliques_info


#include <samson/module/samson.h>


namespace samson{
namespace snalight{


	class cliques_info : public samson::ParserOut
	{

	public:


		void run(KVSetStruct* inputs , TXTWriter *writer )
		{
		}


	};


} // end of namespace samson
} // end of namespace snalight

#endif
