
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_sna_export_cliques
#define _H_SAMSON_sna_export_cliques


#include <samson/module/samson.h>
#include <samson/modules/system/SimpleParserOut.h>
#include <samson/modules/system/Void.h>
#include "samson/modules/snalight/Clique.h"

/***********************************************************
parserOut export_cliques
{
	in snalight.Clique system.Void
	out txt txt

	helpLine "Export cliques to txt files"
}
***********************************************************/

namespace samson{
namespace snalight{


class export_cliques : public samson::ParserOut
{
	Clique clique;
	std::ostringstream output;

public:
	void run(KVSetStruct* inputs , TXTWriter *writer )
	{
		for (size_t i = 0; (i < inputs[0].num_kvs); i++)
		{
			clique.parse(inputs[0].kvs[i]->key);

			output.str(""); //Clear content

			for (int j = 0; (j < clique.nodes_length); j++)
			{
				output << clique.nodes[j].value << " ";
			}
			output << std::endl;

			writer->emit(output.str());
		}

	}

};


} // end of namespace samson
} // end of namespace snalight

#endif
