
/**
 File autogenerated with samsonModuleParser. Please, edit to complete this operation
*/

#ifndef _H_SAMSON_snalight_spread_nodes_to_strong_connections
#define _H_SAMSON_snalight_spread_nodes_to_strong_connections


#include <samson/module/samson.h>


namespace samson{
namespace snalight{


	class spread_nodes_to_strong_connections : public samson::Map
	{

	public:


		void run(  samson::KVSetStruct* inputs , samson::KVWriter *writer )
		{
		}


	};


} // end of namespace samson
} // end of namespace snalight

#endif
